---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    deploymentStrategy:
      type: Recreate
    grafana.ini:
      server:
        root_url: "https://grafana.hef.sh"
    dashboardProviders:
      dashboardProviders.yaml:
        apiVersion: 1
        providers:
          - name: "default"
            orgId: 1
            folder: ""
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
          - name: "network"
            orgId: 1
            folder: "Network"
            type: file
            disableDeletion: true
            editable: false
            options:
              path: /var/lib/grafana/dashboards/network
          - name: "unifi"
            orgId: 1
            folder: "Unifi"
            type: file
            disableDeletion: true
            editable: false
            options:
              path: /var/lib/grafana/dashboards/unifi
    dashboards:
      default:
        # Ref: https://grafana.com/grafana/dashboards/13032
        longhorn-example:
          gnetId: 13032
          revision: 6
          datasource: Prometheus
      unifi:
        # Ref: https://grafana.com/grafana/dashboards/11310
        unpoller-client-dpi:
          gnetId: 11310
          revision: 4
          datasource: Prometheus
        # Ref: https://grafana.com/grafana/dashboards/11311
        unpoller-sites:
          gnetId: 11311
          revision: 4
          datasource: Prometheus
        # Ref: https://grafana.com/grafana/dashboards/11312
        unpoller-usw:
          gnetId: 11312
          revision: 8
          datasource: Prometheus
        # Ref: https://grafana.com/grafana/dashboards/11313
        unpoller-usg:
          gnetId: 11313
          revision: 8
          datasource: Prometheus
        # Ref: https://grafana.com/grafana/dashboards/11314
        unpoller-uap:
          gnetId: 11314
          revision: 9
          datasource: Prometheus
        # Ref: https://grafana.com/grafana/dashboards/11315
        unpoller-clients:
          gnetId: 11315
          revision: 8
          datasource: Prometheus
      network:
        # Ref: https://grafana.com/grafana/dashboards/14127
        metallb:
          gnetId: 14127
          revision: 1
          datasource: Prometheus
        # Ref: https://grafana.com/grafana/dashboards/13665
        speedtest:
          gnetId: 13665
          revision: 1
          datasource: Prometheus
    sidecar:
      dashboards:
        enabled: true
        searchNamespace: ALL
      datasources:
        enabled: true
        searchNamespace: ALL
      notifiers:
        enabled: true
        searchNamespace: ALL
    plugins:
      - grafana-clock-panel
      - natel-discrete-panel
      - grafana-piechart-panel
    serviceMonitor:
      enabled: true
    ingress:
      enabled: true
      annotations:
        hajimari.io/appName: "grafana"
        hajimari.io/enable: "true"
        hajimari.io/icon: "chart-areaspline"
      hosts:
        - grafana.hef.sh
      tls:
        - hosts:
            - grafana.hef.sh
          secretName: grafana.hef.sh-tls-hacks
    persistence:
      enabled: true
      storageClassName: ceph-block
    imageRenderer:
      enabled: false
