apiVersion: apps/v1
kind: Deployment
metadata:
  name: openwakeword
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openwakeword
  template:
    metadata:
      labels:
        app: openwakeword
    spec:
      containers:
        - name: openwakeword
          image: rhasspy/openwakeword-rhasspy:1.8.1
          ports:
            - containerPort: 12202
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 1Gi
                storageClassName: local-path
        - name: config
          configMap:
            name: openwakeword-config
