# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./pvc.yaml
  - ./replication-destination.yaml
  #- ./replication-source.yaml
  - ./secrets.sops.yaml
