apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${CLAIM}"
spec:
  accessModes:
    - ReadWriteOnce
  dataSourceRef:
    apiGroup: volsync.backube
    kind: ReplicationDestination
    name: "${CLAIM}"
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
