apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: "${CLAIM}-restore"
spec:
  trigger:
    manual: restore-once
  restic:
    repository: ${CLAIM}-backup-config
    #copyMethod: Snapshot
    #copyMethod: Clone
    copyMethod: Direct
    volumeSnapshotClassName: longhorn
    storageClassName: longhorn
    # these should match the restored PVC
    accessModes: ["ReadWriteOnce"]
    capacity: ${CAPACITY:-1Gi}
