apiVersion: dbman.hef.sh/v1alpha1
kind: DatabaseServer
metadata:
  name: postgres
  namespace: database
spec:
  #conn_string: "host=192.168.1.6"
  conn_string: "host=postgres-rw.database"
  superuser_secret: superuser-secret
