apiVersion: dbman.hef.sh/v1alpha2
kind: DatabaseServer
metadata:
  name: postgres
  namespace: database
spec:
  #connString: "host=192.168.1.6"
  connString: "host=postgres-rw.database"
  credentials:
    basicAuthSecretRef: superuser-secret
