apiVersion: dbman.hef.sh/v1alpha3
kind: Database
metadata:
  name: db1
  namespace: database
spec:
  credentials:
    basicAuthSecretRef: db1-credentials
  databaseName: db1
  databaseServerRef:
    namespace: database
    name: postgres
---
apiVersion: dbman.hef.sh/v1alpha3
kind: Database
metadata:
  name: db2
  namespace: database
spec:
  databaseName: db2
  databaseServerRef:
    namespace: database
    name: postgres
  ownerRef: db1
