apiVersion: v1
kind: Secret
metadata:
    name: lldap-secret
    namespace: default
stringData:
    SMTP_RELAY_HOSTNAME: ENC[AES256_GCM,data:S5vXjuF7LU8Wg2S2D6M=,iv:hUhQW3CoRPAdKcVqKm8kOGEr+aG84PLFR4dMVn5nngM=,tag:rcPEAP+T/Bz0Jd2oKrAO3g==,type:str]
    SMTP_RELAY_SERVER: ENC[AES256_GCM,data:A8N1NsnOo+M93fC6tpM=,iv:qM1vjKaWMQ4j4vmRcyHKt/L7oe9EvCNwPbCcp3e/HBA=,tag:pe2k/FmhaJ1IxSQJc+Ci6Q==,type:str]
    SMTP_RELAY_USERNAME: ENC[AES256_GCM,data:w1u7kzZNtmRIqHUVbPCo,iv:LBZgKqab1BOAHThO5/UuodweibZbL8WVOvsde+Re0Vc=,tag:LSKJ8fx6DWi9JkXLk3E69g==,type:str]
    SMTP_RELAY_PASSWORD: ENC[AES256_GCM,data:x0fc/Qv0AfoUlmeGsolr+PLFfw==,iv:FXgamsJGza1J6kAy56TelNYNnJPSa+r+KFksB3mUynw=,tag:g3p+0AULZAasEkYYvTW2JA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SkdTZ3U5eWZTWUFpWjV0
            V2o0ajZLbGdlS3MxUzJBa1RTRWhMTEcyMFVRCkNDNmlqZmo5NzQzRU5WendHaDgy
            eWhtMzlEVm03cTJyZlAyZFVCY3d4MlkKLS0tIEF5Wk5BanF6SGRmTDhhNDcrV3o4
            bzlvN25mYWVJVXFDaTZ2UUFxbHdVVXMK9n3HnswwKTQuXO2BxI392KPDzvhN/3m2
            36WN5E61e8oVLARukFndKQFUOKk52YHYPLYPU9QJPu7+CUNlLcsp6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-09T03:22:12Z"
    mac: ENC[AES256_GCM,data:MfShL+BzoNVUAIdWipnlNI56VLi/w/1ROXScyGLpBFr1fiJjNfYxIPARYG/NuhN7iutsOqxB2iOHSpUkZ+hEcTRokeKLT52rXqyniqYgsIUATeStJNC/SAfXMd0BaKAOZQwIkZtNSsDZpvi/GApp04EmW4F81OB2+tvcLmNf4Gs=,iv:1Pn4YKg9MMbhM2PVKKaIkumq6f++/FmySOVMZzbvNQM=,tag:y9aiASrzz/F5PMZQ1ZzhmA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
