apiVersion: apps/v1
kind: Deployment
metadata:
  name: foundry
  namespace: default
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: foundry
  template:
    metadata:
      labels:
        app: foundry
    spec:
      containers:
        - name: foundryvtt
          image: felddy/foundryvtt:13.332.0
          envFrom:
            - secretRef:
                name: foundry-secrets
          env:
            - name: FOUNDRY_HOSTNAME
              value: foundry.${SECRET_DOMAIN}
            - name: FOUNDRY_PROXY_SSL
              value: "true"
            - name: FOUNDRY_PROXY_PORT
              value: "443"
          ports:
            - containerPort: 30000
              name: http
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: foundry-data
