apiVersion: apps/v1
kind: Deployment
metadata:
  name: authz
  namespace: networking
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authz
  template:
    metadata:
      labels:
        app: authz
    spec:
      containers:
        - name: authz
          image: ghcr.io/hef/authz:1.1.2
          ports:
            - containerPort: 50051
              type: TCP
              name: authz-grpc
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "1Gi"
