apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:tG2Y,iv:nve2kfI6ygzh0EFLT0SoCMWfsyGa2qxsO9N0sZMsoQE=,tag:HgWzNKwP+i5KLQzV/RMkqA==,type:str]
    credentials.json: ENC[AES256_GCM,data:BnDknWq3BkDu6iGAEncS10rU6aNeS/lkJ7gNFoUoiI2F9MCI6XQxlKmh7S4aOOpqspY7OS/m80ED41xgI1tOITWYMD4x7sgsPBRnkuDx4wzhKAYWKjNvOJ4XG77K8p7m3V54VnYp38tQzmD7XiCN84xz78/O7nF++sJL34EWNdOXqqy+BoA3NQ+Tf8xqsdFnZqah367jiKb/hAwJ2yR5CUp8iMOOs1Y89cU44e2ADg==,iv:11YNBpDmn1lJlg0vBTelyDtSOsVqfVIiotvSVtFDu8Y=,tag:a84RmwD8BKtqa3X0EB6Whg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoeVA2cEpiQmpaUzBOMEYv
            L3hwQWd5cHpFZjRUZXdyTzVJM2ZXT1cyNndFCmsxbTFGRW5VUUFPVFNOV0xaKzVM
            TWlQTXYwSm1UWnZPdmtIclZ5UTF1UFEKLS0tIGZ4Sll4Y3JHckFNWXJTUVVUaktU
            dy9oZ0FySnNBanlaRHI1N3dzMExtNkUKEY7XOapvmsuqAIolT9QBHZ745+69NQ5/
            KgMowDmZeq84fdrBH48YUiBri2Yvzk69z17xUqNLhyIA7gN7SH1Dfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-30T04:45:40Z"
    mac: ENC[AES256_GCM,data:cghkecY6Z/N0AyiUutAZHuuk8BqfUp+2k25TJKTRHEtVrQiEBzW/xIvnVN2SbCDcbZXFk9W6acy4Oy94fru5bWUSHT25klBbkTRixU4SA2B7z8DpMb0SL9biiAUXahcZR1/YVjeL4zJsn2/NJiXz83bLZkGf+ptGJxkhv/LCfjQ=,iv:vkRl5u3AH50rd4FXHjyS3Sz326fhM38ZuWDl2odXKQA=,tag:Z/+YfbPB879l/SuJl1U/5w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
