apiVersion: v1
kind: Secret
metadata:
    name: wikijs-secrets
    namespace: default
stringData:
    postgresql-password: ENC[AES256_GCM,data:AkAAkTafKlB8AEXvqtB3v9YDc6upgM3GLbsYpeMD88w=,iv:APTOwe2mEedvETLycIFiy9CcceLwVzhOoBuE2AUZAso=,tag:tbNgyJZKdDC+eKsfctx1hA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrR0d6MEJLT3laRFYrazd6
            VGJ4WFJXSXgvK2ZKV0ZFbTNPcmszWXc1WXdZCjlmNHdNcU16b2k1WnR4anZRVHRH
            dHRpWXVQZVdwU1VmOHJEL01ndEp2L3MKLS0tIFhML25GOXFmUm5CNDBzYzc4dEZa
            WVlTWERYR0FNakxZK2ZsSzhuS3VuL3MKL3obbgxo7wOQtiMkqHfQAusCPFxzEYkf
            9e5Uoh5TQW1sJA4biEH/+bkP+QyQElftPmjz/OTgHURFy6GRARnfMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-28T01:59:13Z"
    mac: ENC[AES256_GCM,data:+bQKUHf8UUhWJKN61ViIH01FnhdlpCSpzPCFSjwlkCzBnNOHIvNEnO39srAef+EtslzQQwbgp1vR2e9JVLxGu+5eVrMUy1CJVDlxpO2O1qiGKivGJq7i0wla+nGVnCSpgWdUxrZiFjoh7EEGVs6SftWUp6wPlIQPF5nIIGn8QzI=,iv:pRarYo7XalocfU2KLDrzFYDjqVdaCYRKMG5EqIrL/1k=,tag:aSHPA7vJpc5lmZajOQa0GQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
