---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: external-snapshotter
  namespace: flux-system
spec:
  interval: 30m0s
  ref:
    tag: 6.3.2
  url: https://github.com/kubernetes-csi/external-snapshotter
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-ops
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./client/config/crd
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: external-snapshotter
