---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: external-snapshotter
  namespace: kube-system
spec:
  interval: 30m0s
  ref:
    tag: "v6.3.4"
  url: https://github.com/kubernetes-csi/external-snapshotter
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-snapshotter-crds
  namespace: kube-system
spec:
  interval: 10m0s
  path: ./client/config/crd
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: external-snapshotter
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-snapshotter
  namespace: kube-system
spec:
  interval: 10m0s
  path: ./deploy/kubernetes/snapshot-controller
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: external-snapshotter
