---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foundry-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-static
  claimRef:
    name: foundry-data
