apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
    namespace: default
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:sxp5Lxs7alTFjQ7abK8+SimUkv8ArPzALh6D70wXGSnjolOA2dSpiLVftFoeW9eF4wkgQtPq1CTj6G5oGsR0sfY9VMm/0U9DSrbAMr89Phw9IaaOh/uM0WbImMWsSx+0nJJH1lLCVLRn0/9rQVN+wUM=,iv:QUX/1aOCX/zHUeQ83MQYns6AGqBbP90Yewra0jza8kg=,tag:wq0xCImFsrt0qBPjkli9Fw==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:8VjWoeZ8lRf8FwqWHm1ZtO4Bzpg3XagaQeKniL46K3aocGX8mjwH,iv:0gurl/trX2cb5OdF5VUblE4sj4g+dEU16z+GcCF4jfk=,tag:Zkc9T3k5azqEBT3sqxM4hA==,type:str]
    SMTP_FROM: ENC[AES256_GCM,data:ttx0rkWJ2KDDlPIUCjz/8+37,iv:gHnmLwS352bC22KaBux3mRx9vednI2lLbLyyakev+4M=,tag:3sAgiwGyVdViSuE57zGmEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6M0NYNXhDM2NncW5LL2Fp
            emx0NTlUb09aTHRXeHpWcStIUXZwU29uOWpZCkMxU1lpaG4rZmwvelR0ZzhhUGhs
            dkpRam9MVytMSHhYNkhxTFNZM2pEK2sKLS0tIEcyTlRrSG13czQ3TkUyZFNXeGFE
            NEdXdWc5UkhHQ2o0VGt2OVJsSzNJYVEKm8pf+KFB8JGA9Jgqm+WjVTL/bLylmNn8
            9GktFJm08TCf0qksufbcqWjzRd2qBMXznCpPGozQiv1p8W0wLdej/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-03T21:26:17Z"
    mac: ENC[AES256_GCM,data:t1/PtWDI5HGRqgbUUVw0x0fpV+Kd4DRADoWBZGgBSg5BHT3iOnfi6IED1gatUbW3rZC0sHK7imnBpPDStIgFlUwiut+byqpALdcoRQND/RFYrlC9+igeDDKb39V4MjCKuCYOdXnzflirZTqR4TiWKpol61G/dcYSe9AXAqnhmTY=,iv:wj961RwArJQFgIzzBZsPTPhc1eSqltEPovvX/Q5sOyg=,tag:9Oh6flgbP3hpTdqD0ySW3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-credentials
    namespace: default
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:y6RKGzv5rZJ0Bwo=,iv:rMbmRyQKdtWexQ4v5wcGGv79SH1dx0IjGvJd9+IlN98=,tag:reZnToECCwae8ysPBsnjOw==,type:str]
    password: ENC[AES256_GCM,data:3Fl/fntQ3BrLf598xtyWVmjXVefqIiSc8NNgOf7nO8A=,iv:YKw/A0PJydGuYNry3ykAiWCx+iN6VrJHmQXPl8UkRg4=,tag:9OwdWOSvrJEucez7q23ZbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6M0NYNXhDM2NncW5LL2Fp
            emx0NTlUb09aTHRXeHpWcStIUXZwU29uOWpZCkMxU1lpaG4rZmwvelR0ZzhhUGhs
            dkpRam9MVytMSHhYNkhxTFNZM2pEK2sKLS0tIEcyTlRrSG13czQ3TkUyZFNXeGFE
            NEdXdWc5UkhHQ2o0VGt2OVJsSzNJYVEKm8pf+KFB8JGA9Jgqm+WjVTL/bLylmNn8
            9GktFJm08TCf0qksufbcqWjzRd2qBMXznCpPGozQiv1p8W0wLdej/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-03T21:26:17Z"
    mac: ENC[AES256_GCM,data:t1/PtWDI5HGRqgbUUVw0x0fpV+Kd4DRADoWBZGgBSg5BHT3iOnfi6IED1gatUbW3rZC0sHK7imnBpPDStIgFlUwiut+byqpALdcoRQND/RFYrlC9+igeDDKb39V4MjCKuCYOdXnzflirZTqR4TiWKpol61G/dcYSe9AXAqnhmTY=,iv:wj961RwArJQFgIzzBZsPTPhc1eSqltEPovvX/Q5sOyg=,tag:9Oh6flgbP3hpTdqD0ySW3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
