apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
    namespace: default
stringData:
    z: ENC[AES256_GCM,data:pA==,iv:eofqbLK01HMfjas55SJoB6mveJGQx2fYQ47bqA7RdWw=,tag:AKqtcLS4O4j5lOycZgBcJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6M0NYNXhDM2NncW5LL2Fp
            emx0NTlUb09aTHRXeHpWcStIUXZwU29uOWpZCkMxU1lpaG4rZmwvelR0ZzhhUGhs
            dkpRam9MVytMSHhYNkhxTFNZM2pEK2sKLS0tIEcyTlRrSG13czQ3TkUyZFNXeGFE
            NEdXdWc5UkhHQ2o0VGt2OVJsSzNJYVEKm8pf+KFB8JGA9Jgqm+WjVTL/bLylmNn8
            9GktFJm08TCf0qksufbcqWjzRd2qBMXznCpPGozQiv1p8W0wLdej/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-03T20:56:43Z"
    mac: ENC[AES256_GCM,data:FgN39PrnGn11PSQbTSiDJfBDRA1cPuUnB4oLue8ZuMDpoBa2aaiquFFB/+vtuaR/cM10bgNGjvLuwmao3hwmUtManV6fOG9BTtMaRKk8vdDM+f1ZMfYc++1ePOg+WnkjhdB4AS6qr6OqBorq75mU6wCzXTtTBWiPcPuGzqNQ70I=,iv:0UJMylSqfD5iCTMl//9z1LlhEKB1ryQtyAo0ScQq4AI=,tag:+XNZoYKHVfzQSz/iwlqH6Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-credentials
    namespace: default
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:y6RKGzv5rZJ0Bwo=,iv:rMbmRyQKdtWexQ4v5wcGGv79SH1dx0IjGvJd9+IlN98=,tag:reZnToECCwae8ysPBsnjOw==,type:str]
    password: ENC[AES256_GCM,data:3Fl/fntQ3BrLf598xtyWVmjXVefqIiSc8NNgOf7nO8A=,iv:YKw/A0PJydGuYNry3ykAiWCx+iN6VrJHmQXPl8UkRg4=,tag:9OwdWOSvrJEucez7q23ZbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6M0NYNXhDM2NncW5LL2Fp
            emx0NTlUb09aTHRXeHpWcStIUXZwU29uOWpZCkMxU1lpaG4rZmwvelR0ZzhhUGhs
            dkpRam9MVytMSHhYNkhxTFNZM2pEK2sKLS0tIEcyTlRrSG13czQ3TkUyZFNXeGFE
            NEdXdWc5UkhHQ2o0VGt2OVJsSzNJYVEKm8pf+KFB8JGA9Jgqm+WjVTL/bLylmNn8
            9GktFJm08TCf0qksufbcqWjzRd2qBMXznCpPGozQiv1p8W0wLdej/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-03T20:56:43Z"
    mac: ENC[AES256_GCM,data:FgN39PrnGn11PSQbTSiDJfBDRA1cPuUnB4oLue8ZuMDpoBa2aaiquFFB/+vtuaR/cM10bgNGjvLuwmao3hwmUtManV6fOG9BTtMaRKk8vdDM+f1ZMfYc++1ePOg+WnkjhdB4AS6qr6OqBorq75mU6wCzXTtTBWiPcPuGzqNQ70I=,iv:0UJMylSqfD5iCTMl//9z1LlhEKB1ryQtyAo0ScQq4AI=,tag:+XNZoYKHVfzQSz/iwlqH6Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
