apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hass-config
  namespace: default
spec:
  storageClassName: longhorn-static
  claimRef:
    namespace: default
    name: hass-config
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
