apiVersion: dbman.hef.sh/v1alpha3
kind: Database
metadata:
  name: lldap
  namespace: default
spec:
  credentials:
    basicAuthSecretRef: lldap-credentials
  databaseName: lldap
  databaseServerRef:
    namespace: database
    name: postgres
  prune: false
