apiVersion: v1
kind: Secret
metadata:
    name: lldap-secret
    namespace: default
stringData:
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:0BPhlQvEeEST6IO4zNQnR1K1LdUFNmmQsfhUi66xw+8=,iv:0xKOb37hCVOJp8dEShE5Ll/VSDHpyoE1jEw+yJ7vW68=,tag:Ya64o7ayY6jw2e1fn3SGCw==,type:str]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:bVhLmxtEVvTXV/tr2PR9TWC134S5o+HMVM9MTZ//cc4=,iv:pIvlMzFj7AhjbJ/n0BMhC/48A4imvn9udQy8Zs0R+T0=,tag:2lLFudgEhPJGs+Cl7cZxsg==,type:str]
    #ENC[AES256_GCM,data:gwao2Xk7RG66cZJve2oQm4Vq68REQMPG+/JOu6q7InAxwEJ+YA==,iv:kv5s0R/lgqQnXbSLC60NVlh8RHZWlg9BLk/l8UanGus=,tag:j60WlvreAy2DSjR8pjnAPg==,type:comment]
    #ENC[AES256_GCM,data:HbjXenZJQJRDbAO3sJC0XOsRyVKo7p6TH+yWbQBYF4AwuOiEwbNL7UqKsQRbCYdO0JllUck=,iv:DM76B0SVwK1eKGGwbu+mhM3qhEzFinX1UuL/mdNnLfk=,tag:p+k8AiNn+qm9uVEGNWFYuA==,type:comment]
    LLDAP_SERVER_KEY_SEED: ENC[AES256_GCM,data:KHJmq1MlRq4NGkLxbwBeMpMyWQws7VLDYoXA7zYaQ1w=,iv:VFIkGMlFk7+sU/XCip19NPu3MuenesfxEcPOC+NSdlE=,tag:LeLVwwHsBxdi93w6hjB4Qw==,type:str]
    LLDAP_DATABASE_URL: ENC[AES256_GCM,data:ErM0uRkUmRihfRZvE44i1NLeP0G4KZDGLQEzP3tLCLOExTig2EB2jXjm4WT2/nJkX+BSq3UNzjaedoI833DmD6t/UOiR4+JzjjNPXGqeEPI6lHaxXKL4faOGiSVDiQ==,iv:fZizZxeQ5rsdUvMcvyDD5Q/Vknoy4RW5Glo33ngVaf4=,tag:Wy71ca2lkF5ITw/Rb+4LeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6M0NYNXhDM2NncW5LL2Fp
            emx0NTlUb09aTHRXeHpWcStIUXZwU29uOWpZCkMxU1lpaG4rZmwvelR0ZzhhUGhs
            dkpRam9MVytMSHhYNkhxTFNZM2pEK2sKLS0tIEcyTlRrSG13czQ3TkUyZFNXeGFE
            NEdXdWc5UkhHQ2o0VGt2OVJsSzNJYVEKm8pf+KFB8JGA9Jgqm+WjVTL/bLylmNn8
            9GktFJm08TCf0qksufbcqWjzRd2qBMXznCpPGozQiv1p8W0wLdej/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-02T02:11:22Z"
    mac: ENC[AES256_GCM,data:tCcT/XxajZbNDVnu64qYR3E477y3H/uZpdPUmKaZVsY//qjiZbwoz6fIwe8gx2bZd9Xuzh3wRdVMcOreBXamzeGvFkCWuLNKY13kFWJ8Y4o473lmNPVBL+ZQVwtxhsPIdWyBMEyNkC/tTAuH6xBLgaXXY0ON1/A4nuVUFrfQyhE=,iv:hldQx32lGC1F+BRK9LmtJykhci464fWIqioaPP/PL4I=,tag:/Rf2MiFQiKltk4snyQT++g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: lldap-credentials
    namespace: default
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:coJfBLo=,iv:MvrhVPg8ZRMBXQZEeSgSgjXsi8SdEJErFuP8OA7l2BA=,tag:FkCNFT1m8bvZyZb818EaqQ==,type:str]
    password: ENC[AES256_GCM,data:QfVlV4Hnp47JvtESMQfFuZHAB+/JnESo49r0+i9wmS8=,iv:QmSTLd24N0FMWlqsdZSslx4V14ASYYf6w8FLW+UdoY8=,tag:MRPW3s6pFdEm/IAp+TCvpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6M0NYNXhDM2NncW5LL2Fp
            emx0NTlUb09aTHRXeHpWcStIUXZwU29uOWpZCkMxU1lpaG4rZmwvelR0ZzhhUGhs
            dkpRam9MVytMSHhYNkhxTFNZM2pEK2sKLS0tIEcyTlRrSG13czQ3TkUyZFNXeGFE
            NEdXdWc5UkhHQ2o0VGt2OVJsSzNJYVEKm8pf+KFB8JGA9Jgqm+WjVTL/bLylmNn8
            9GktFJm08TCf0qksufbcqWjzRd2qBMXznCpPGozQiv1p8W0wLdej/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-02T02:11:22Z"
    mac: ENC[AES256_GCM,data:tCcT/XxajZbNDVnu64qYR3E477y3H/uZpdPUmKaZVsY//qjiZbwoz6fIwe8gx2bZd9Xuzh3wRdVMcOreBXamzeGvFkCWuLNKY13kFWJ8Y4o473lmNPVBL+ZQVwtxhsPIdWyBMEyNkC/tTAuH6xBLgaXXY0ON1/A4nuVUFrfQyhE=,iv:hldQx32lGC1F+BRK9LmtJykhci464fWIqioaPP/PL4I=,tag:/Rf2MiFQiKltk4snyQT++g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
