apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:0BPhlQvEeEST6IO4zNQnR1K1LdUFNmmQsfhUi66xw+8=,iv:0xKOb37hCVOJp8dEShE5Ll/VSDHpyoE1jEw+yJ7vW68=,tag:Ya64o7ayY6jw2e1fn3SGCw==,type:str]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:bVhLmxtEVvTXV/tr2PR9TWC134S5o+HMVM9MTZ//cc4=,iv:pIvlMzFj7AhjbJ/n0BMhC/48A4imvn9udQy8Zs0R+T0=,tag:2lLFudgEhPJGs+Cl7cZxsg==,type:str]
    #ENC[AES256_GCM,data:gwao2Xk7RG66cZJve2oQm4Vq68REQMPG+/JOu6q7InAxwEJ+YA==,iv:kv5s0R/lgqQnXbSLC60NVlh8RHZWlg9BLk/l8UanGus=,tag:j60WlvreAy2DSjR8pjnAPg==,type:comment]
    #ENC[AES256_GCM,data:HbjXenZJQJRDbAO3sJC0XOsRyVKo7p6TH+yWbQBYF4AwuOiEwbNL7UqKsQRbCYdO0JllUck=,iv:DM76B0SVwK1eKGGwbu+mhM3qhEzFinX1UuL/mdNnLfk=,tag:p+k8AiNn+qm9uVEGNWFYuA==,type:comment]
    #ENC[AES256_GCM,data:ArHYee+j9mV68WG+mZRuRXSgI1xjpx7BmyCTm4jQkykZmUslzokZiznwft54Y5321mhA008=,iv:4T3ttAqQjcHKkjEtQKqdaB76Oc1uNXliXrXJgXv+xR0=,tag:9GIxaocSVct+duux0f78eQ==,type:comment]
    #ENC[AES256_GCM,data:OzSx01v4PYaJ/jnHZi516jnEq5dsTsGEREg0wxuijYwk3uYfwGAwGYiC5S0MSkQZtjxADjE0huNorIj494Pzi/cacEt1wQlXaRjesTUo9VQVQX3xHx5ING/s5/Z34S+LOZX4AhSMHeVPFYB8aqfbGOUNvidPaqc=,iv:qZaQlpCer76t7mc7T+QuAgxSqgH8UuZsDITSx+cmlPQ=,tag:DuxMOLy1XcNNbSANCvtRsg==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6M0NYNXhDM2NncW5LL2Fp
            emx0NTlUb09aTHRXeHpWcStIUXZwU29uOWpZCkMxU1lpaG4rZmwvelR0ZzhhUGhs
            dkpRam9MVytMSHhYNkhxTFNZM2pEK2sKLS0tIEcyTlRrSG13czQ3TkUyZFNXeGFE
            NEdXdWc5UkhHQ2o0VGt2OVJsSzNJYVEKm8pf+KFB8JGA9Jgqm+WjVTL/bLylmNn8
            9GktFJm08TCf0qksufbcqWjzRd2qBMXznCpPGozQiv1p8W0wLdej/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-17T00:31:48Z"
    mac: ENC[AES256_GCM,data:ZOkIEaKYn3iuiUUPebv4qluS7B/bjQxCfWzBoNoZcxVJ1B2y1sz1yIyaeyTe7Od8Qd8IM5XENMzNyMEC/N9YRRlGWQaItG5U+/xR9d+XGblKmTbOb28uFskXXZSZQ6nuk1cXuMdU8ynrtHaiPNTXQQio4nLBkZ3Jlnl0ml5XB6c=,iv:/DvuJZuqkRNzyo7h33dhxgsQv0jNTCxN7CcriRuOR6s=,tag:rrutzY7YhFqAqdRhoZpibQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
