---
- hosts:
    - master
    #- worker
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 5 seconds...
      pause:
        seconds: 5
  tasks:
    - name: Cilium
      ansible.builtin.include_tasks: tasks/cilium.yaml
    - name: cruft
      ansible.builtin.include_tasks: tasks/cruft.yaml
