---
- hosts:
    - master
    - worker
  become: true
  gather_facts: true
  any_errors_fatal: true
  tasks:
    - name: upgrade
      ansible.builtin.apt:
        upgrade: full
        update_cache: true
        cache_valid_time: 3600
        autoclean: true
        autoremove: true
      register: apt_upgrade
      retries: 5
      until: apt_upgrade is success
    - block:
        - name: Upgrade all packages to the latest version
          apt: update_cache=yes upgrade=full
        - name: Ensure update-manager-core is installed.
          apt: name=update-manager-core state=present
        - name: Run do-release-upgrade non-interactively.
          command: do-release-upgrade -f DistUpgradeViewNonInteractive
        - name: Reboot the server.
          reboot:
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version != '22.04'
