---
- hosts:
    - master
    - worker
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 5 seconds...
      pause:
        seconds: 5
  roles:
    - ubuntu
    - devsec.hardening.os_hardening
    - devsec.hardening.ssh_hardening
  vars:
    sysctl_overwrite:
      net.ipv4.ip_forward: 1
    ssh_permit_root_login: 'without-password'
    sftp_enabled: true
    # newer ubuntu doesn't have syslog group
    # https://github.com/dev-sec/ansible-collection-hardening/blob/4cb67edbe5a523d7e38f1824a828f05a04645b36/roles/os_hardening/vars/Ubuntu.yml#L65
    os_mnt_var_log_group: 'root'
