apiVersion: apps/v1
kind: Deployment
metadata:
  name: netshoot
  namespace: blocky
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: netshoot
    spec:
      containers:
        - name: netshoot
          image: nicolaka/netshoot:latest
          imagePullPolicy: Always
          command:
            - /bin/sh
            - -c
            - sleep infinity
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
  selector:
    matchLabels:
      app: netshoot

