---
kubernetes:
  #ansible_user: ubuntu
  children:
    master:
      hosts:
        k8s-0:
          ansible_host: 192.168.1.157
        k8s-1:
          ansible_host: 192.168.1.174
        k8s-2:
          ansible_host: 192.168.1.141
    worker:
      hosts:
        k8s-3:
          ansible_host: 192.168.1.165
