---
kubernetes:
  children:
    master:
      hosts:
        k8s-0:
          ansible_host: 192.168.4.14
        k8s-1:
          ansible_host: 192.168.4.15
        k8s-2:
          ansible_host: 192.168.4.16
    worker:
      hosts:
        k8s-3:
          ansible_host: 192.168.4.17
