---
kubernetes:
  children:
    master:
      hosts:
        k8s-0:
          ansible_host: 192.168.4.6
        k8s-1:
          ansible_host: 192.168.4.7
        k8s-2:
          ansible_host: 192.168.4.8
    worker:
      hosts:
        k8s-3:
          ansible_host: 192.168.4.9
