apiVersion: apps/v1
kind: Deployment
metadata:
  name: piper
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: piper
  template:
    metadata:
      labels:
        app: piper
    spec:
      containers:
        - name: piper
          image: rhasspy/wyoming-piper:1.3.0
          args: [ "--voice", "en-us-lessac-low" ]
          ports:
            - containerPort: 10200
          volumeMounts:
          - name: data
            mountPath: /data
      volumes:
        - name: data
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes: [ "ReadWriteOnce" ]
                resources:
                  requests:
                    storage: 1Gi
                storageClassName: local-path