---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app minio
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: operator
      version: 5.0.14
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    congress:
      ingress:
        enabled: true
        ingressClassName: internal
        host: minio.${SECRET_DOMAIN}
