apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: discord
  namespace: flux-system
spec:
  type: discord
  username: Spidy Bot
  channel: general
  secretRef:
    name: discord-webhook-url
