apiVersion: v1
kind: Service
metadata:
  name: rustdesk-server
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: rustdesk.${SECRET_DOMAIN}
    io.cilium/lb-ipam-ips: 192.168.1.11
spec:
  selector:
    app: rustdesk-hbbs
  ports:
    - name: "21114"
      port: 21114
      protocol: TCP
      containerPort: 21114
    - name: "21115"
      port: 21115
      protocol: TCP
      targetPort: 21115
    - name: "21116-tcp"
      port: 21116
      protocol: TCP
      targetPort: 21116
    - name: "21116-udp"
      port: 21116
      protocol: UDP
      targetPort: 21116
    - name: "21118"
      port: 21118
      protocol: TCP
      targetPort: 21118
---
apiVersion: v1
kind: Service
metadata:
  name: rustdesk-relay
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: rustdesk-relay.${SECRET_DOMAIN}
    io.cilium/lb-ipam-ips: 192.168.1.11
spec:
  type: LoadBalancer
  selector:
    app: rustdesk-hbbr
  ports:
    - name: "21117"
      port: 21117
      protocol: TCP
      targetPort: 21117
    - name: "21119"
      port: 21119
      protocol: TCP
      targetPort: 21119
---
