kind: Secret
ansible_user: ENC[AES256_GCM,data:H2x4QYCB,iv:+1jJ8jsOc71a59oFsCe7/UG4qIy4e7k7MWKmXyOIhrA=,tag:oHDz/YLzNCvm0h1sHi8iAA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:ielXA/PlXwsN9yZRf1HEFYsIrpc=,iv:vdvNlB311mQUyT1eWezfwDScJon2WK5x1SgT/Q5GtAU=,tag:1k+1/b5c9RodVsjkgV06SQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlMG9XV3Mva2ZDZU5majY1
            c211cjZsMUFhUnF0THUwZVVvZFRYQTZpU2wwClphQXNWbEJkT3UzWmpYYktXOXRt
            SlA3L29GM3YzUlFHalFlb2xTK0l6eTQKLS0tIG5CK2xlaFY3ZmhJSnZpbFJQRnYr
            cTJrOERhNUs3TFhnS3NXMjFkb200N0EKrSNFFwHeDY+ZlgerUcdw4Ny2ygLpmuiI
            P70uOL2aQAfHC8e447+YvpphL/afelgk6jHUvuNAcggxO7Nu5+IsQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-06T01:15:53Z"
    mac: ENC[AES256_GCM,data:bG22i6ChG0OHYorrHCfLzKf9qFBIzhCW4qjT4dBBE8rgr4Bk6dOO/Jc9ZzFKBvQU/+ynCYBqvkzZp2HVGBRJJtSRr8/o2ppvSeW1XKnE4MAx4M8UlT+IWQL5H0b6HVgW8V8vAtuoZu2Q8rR9gV7bUx8XEfsJD+SfaH0GlUjlBdA=,iv:c9vCV6GaDN96kAUj38tSvOcDm+wK5al+f3mDW+7btMQ=,tag:T2mHp1ePgpOTH6JXA9RStg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.9.2
