kind: Secret
ansible_user: ENC[AES256_GCM,data:H2x4QYCB,iv:+1jJ8jsOc71a59oFsCe7/UG4qIy4e7k7MWKmXyOIhrA=,tag:oHDz/YLzNCvm0h1sHi8iAA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:t8VNGMNUZcjbVrFJUxa9xSI=,iv:OoMHyt0Si6RPLAVZAzsdY3HakKmXi1zZbpKd6lReTqc=,tag:WvDWXEibK5giSIYqm9jmFA==,type:str]
sops:
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlMG9XV3Mva2ZDZU5majY1
            c211cjZsMUFhUnF0THUwZVVvZFRYQTZpU2wwClphQXNWbEJkT3UzWmpYYktXOXRt
            SlA3L29GM3YzUlFHalFlb2xTK0l6eTQKLS0tIG5CK2xlaFY3ZmhJSnZpbFJQRnYr
            cTJrOERhNUs3TFhnS3NXMjFkb200N0EKrSNFFwHeDY+ZlgerUcdw4Ny2ygLpmuiI
            P70uOL2aQAfHC8e447+YvpphL/afelgk6jHUvuNAcggxO7Nu5+IsQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-26T00:40:34Z"
    mac: ENC[AES256_GCM,data:EVvucbz1VRNa7q+XzhF6d8fK3LXqrlUz9y2xxxG8vd6uEEDIY+FyYqCvJ5CslYNR8dBy4KiRwlbgZO6wgo56EWVBbMkFSzHIaeZJJvP8keVE3UnwrLdjbbqEAzOV7Oa92emG4NzOSMDezrpMQ5RO3umOpEJo076FLsgNoP9gOWY=,iv:y9bVdBMfD+Rs+hGlw4HSQ8JcZCru4vePajwn4+q0kno=,tag:aUWcCHvuJ/uIEeqUgK+zJw==,type:str]
    unencrypted_regex: ^(kind)$
    version: 3.10.2
