---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mealie
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/mealie-recipes/mealie
              tag: v1.5.1
            env:
              BASE_URL: https://mealie.${SECRET_DOMAIN}
    service:
      main:
        controller: main
        ports:
          http:
            port: 8080
    ingress:
      main:
        hosts:
          - host: mealie.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: ImplementationSpecific
                service:
                  identifier: main
                  port: http
