apiVersion: apps/v1
kind: ConfigMap
metadata:
  name: gitea-config
  namespace: default
data:
  GITEA__database__DB_TYPE: postgres
  GITEA__database__HOST: postgres-rw.database.svc.cluster.local:5432
  GITEA__database__NAME: gitea
  GITEA__database__USER: gitea
