apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
        - env:
            - name: DOMAIN
              value: git.${SECRET_DOMAIN}
            - name: DISABLE_SSH
              value: "true"
            - name: ROOT_URL
              value: https://git.${SECRET_DOMAIN}
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: SECRET_KEY
                  name: gitea-secrets
          image: gitea/gitea:1.21.4
          imagePullPolicy: Always
          name: gitea
          ports:
            - containerPort: 3000
              protocol: TCP
              name: http
          resources:
            limits:
              cpu: "100m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          volumeMounts:
            - mountPath: /data/
              name: gitea-storage-volume
      volumes:
        - name: gitea-storage-volume
          persistentVolumeClaim:
            claimName: gitea-storage
