apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-storage
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn-static
