apiVersion: v1
kind: Secret
metadata:
    name: gitea-secrets
    namespace: default
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:yV4IUowXuriRNN0K3gejtIO8Tropz8dO3nO4YNbSxes1jTRAPlf+OD/cHRpPzovWfYc+T+gsLvTMoBT8ttnXvh8xrRenOuqsC0zguZ4fZTQrXYKXvBPSaxQarK6+wfjj5TdNFg==,iv:K+ll+Yo29C79BfMpIIfJ0RRK/OkkFKqCoGStQYr9QE4=,tag:OMbqF8+99D+A0lQRkAaOPA==,type:str]
    GITEA__database__PASSWD: ENC[AES256_GCM,data:YdFr7FooxHUIAECPJLZt9jWsc2/t3k/INOYoLUhd1N8=,iv:u4mPjtiyw0NPKDJ3UbcfIAErwcX/HwkF1r7ZqEGOroI=,tag:K7an20YW2Kfxu7bkq5x3Yg==,type:str]
    z: ENC[AES256_GCM,data:jTLVPmPPXFOm9sUUVUA0tBsEFjy9paC1fu6k5coaBYI5JXs6rWOqTkk/Ch8CbrwA8Zef3KuMIAmO2BzSQZaEgLJGKYaJaZfg,iv:qxfqNTLwhaEmrrPtNodAbuqHFKuJCuiLMDlzrvYFRig=,tag:ytC5mgwJuiBgsSQwdHKy1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4cDdRc1hQTGo0eGNwb3Jh
            WE9kZ2t2WEZJRXpDcUpjVFpKWEpJSTBSQWtzCnRIOWdQSFhvcFQwWDlsZHV0V0FW
            YmNDeWZ6aWRqeTJKZHp5WGkyQ25iWUkKLS0tIFBxZGNIaUpFSFlsUFQ1TmJkVW5y
            d0VIT3FoSGpEZ0F1RFd1ZE5IcTAyRUEK60/Gx93iRa7fjV7pfaBQ5au9dezYjIS5
            B0EeRknpM2sGEv0RHTIu5nohJGiEJHWtTlyLQLldzkQykCQLXv6KBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-11T22:53:04Z"
    mac: ENC[AES256_GCM,data:Z48+fuQBHGRcPHYzAC+05uTfLqcrkYK5WI4F4yOMXZyWg7W+mzEtDRHAZEM086DZ4L/W9g2A8aJwQU2A2w76u8+q/S14EikfT0UbPkSQler8auzYsMbKkYd7/abZN4J3JP5Qs+aokE2Id7XJ+k9nQG63M1hp9FDNHHReigQ0e2I=,iv:tdSeU+GNtCTNFZWc53aZhV3QoU/jVXQo8Z4DBKgnQ64=,tag:4e3XZIqq6wrA5fsOqmnorA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gitea-credentials
    namespace: default
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:qDrCQZU=,iv:dqRGBarCKjIxHN/3iPi8DjLGEJRyk3Ubb9HsQXdD5HA=,tag:xpFbuB1SixhrxsGqm+DTdA==,type:str]
    password: ENC[AES256_GCM,data:IwOaCHIGdaZWAHZgWSmqZfzy2bLG54JkTKjReWaLXQM=,iv:nNflz5SScyXWiLcJOddUNXuj2S3GWRQ3zbsMQYbxGJw=,tag:RRcp2ETMV9G3oeojwZlsXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4cDdRc1hQTGo0eGNwb3Jh
            WE9kZ2t2WEZJRXpDcUpjVFpKWEpJSTBSQWtzCnRIOWdQSFhvcFQwWDlsZHV0V0FW
            YmNDeWZ6aWRqeTJKZHp5WGkyQ25iWUkKLS0tIFBxZGNIaUpFSFlsUFQ1TmJkVW5y
            d0VIT3FoSGpEZ0F1RFd1ZE5IcTAyRUEK60/Gx93iRa7fjV7pfaBQ5au9dezYjIS5
            B0EeRknpM2sGEv0RHTIu5nohJGiEJHWtTlyLQLldzkQykCQLXv6KBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-11T22:53:04Z"
    mac: ENC[AES256_GCM,data:Z48+fuQBHGRcPHYzAC+05uTfLqcrkYK5WI4F4yOMXZyWg7W+mzEtDRHAZEM086DZ4L/W9g2A8aJwQU2A2w76u8+q/S14EikfT0UbPkSQler8auzYsMbKkYd7/abZN4J3JP5Qs+aokE2Id7XJ+k9nQG63M1hp9FDNHHReigQ0e2I=,iv:tdSeU+GNtCTNFZWc53aZhV3QoU/jVXQo8Z4DBKgnQ64=,tag:4e3XZIqq6wrA5fsOqmnorA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gitea-storage-backup-config
    namespace: default
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:LDlDy8YDMATaS5tvssiZc2Lhd7nfyRMR1LJ9p3f/kBq/jMkTU+vKdUSzHGoOQMA2kjdqrkgilRGyUtsXiltE4a4V,iv:IlIqEsZINYhAKxRT91/pljduXX6pqOAVg4zq/oJ11wY=,tag:0eyUn7gwho4xc9RVRyvV8A==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:lGdXtP120sbHc0u5cWS9R20CHmrtSoPVUEMLbbGkRkYSMiODzOZ5Xb5+mzsx1Vx9OotBm8RXpynHLMrTBc4t9R7Kjb5siBuM+f0g5tC0fuEhaYVTqWwY3Xf1IvfFc/sjQfZut2V/uWBJgG8s15l4uJFbRl0aLjdhd5zu/Q0At8k=,iv:tEY87oMpu1CovLtnGmIxAEElcfffFSuDI2TSQIMMKmo=,tag:3H/idXcl4iKe5pdDqFTF8A==,type:str]
    #ENC[AES256_GCM,data:+m0j6aaXaZpvDzJl2RgV0KohFrbLfLYCuoHsxJEy2x4qlkjgPg6ftS0=,iv:xpMKaAsl79XW9eB3d8K7U4a03RsBag67NRC2rR2HOco=,tag:K6uLExvCr62bCkkPc76sfg==,type:comment]
    #ENC[AES256_GCM,data:uSbfx4/r4fp/kQXmhdAlmqy5CYen7rr6xN172n3575CIahDN4S+y9nGqp3NSSZ20TqqfvTIoj97/v6mBIFGSNXOTtUOcPA==,iv:1XLw0JClgslpK7VTbDoxDN1BvZ1gmMXnwjQoUZFk3Eo=,tag:cCFM6ii0NfWooSMWx/tSgw==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ZhIs6hDWBXk6CjhObGAny3xOqfBP+1CSyQ==,iv:WN9pQbr8uaDUdETdmprM6nUCsgevIrmO/QPPSjbef4A=,tag:hUDtE+0h84Lz2RMPm+qaqQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:IbfujQaq6XuRCOrc1ehYqaZDd9S3c5aY/VMOyXhzMA==,iv:BjveKYvXWyMI7J1+1zD93H9mio2j/8mqOU+KHIZYvaM=,tag:CyZHba6j9PV+6agvdwhk5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4cDdRc1hQTGo0eGNwb3Jh
            WE9kZ2t2WEZJRXpDcUpjVFpKWEpJSTBSQWtzCnRIOWdQSFhvcFQwWDlsZHV0V0FW
            YmNDeWZ6aWRqeTJKZHp5WGkyQ25iWUkKLS0tIFBxZGNIaUpFSFlsUFQ1TmJkVW5y
            d0VIT3FoSGpEZ0F1RFd1ZE5IcTAyRUEK60/Gx93iRa7fjV7pfaBQ5au9dezYjIS5
            B0EeRknpM2sGEv0RHTIu5nohJGiEJHWtTlyLQLldzkQykCQLXv6KBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-11T22:53:04Z"
    mac: ENC[AES256_GCM,data:Z48+fuQBHGRcPHYzAC+05uTfLqcrkYK5WI4F4yOMXZyWg7W+mzEtDRHAZEM086DZ4L/W9g2A8aJwQU2A2w76u8+q/S14EikfT0UbPkSQler8auzYsMbKkYd7/abZN4J3JP5Qs+aokE2Id7XJ+k9nQG63M1hp9FDNHHReigQ0e2I=,iv:tdSeU+GNtCTNFZWc53aZhV3QoU/jVXQo8Z4DBKgnQ64=,tag:4e3XZIqq6wrA5fsOqmnorA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
