apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - database
  - kube-system
  - longhorn
  - networking
  #- snapshot-controller
  - system-upgrade
  - volsync
  - https://github.com/kubernetes-csi/external-snapshotter/tree/v6.3.2/deploy/kubernetes/snapshot-controller
