# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:3AiZ3Qkj,iv:nrwYz8tsc93jQ7fiSfM2cdauqGLwa2jnR/VVow1YQf8=,tag:1Px54t0B3RqxAsbWwLTwUw==,type:str]
    SECRET_TZ: ENC[AES256_GCM,data:hW8WqPtzBPi/PtQpPzyH,iv:ebFWbl9+REQ0wqJUrT1TixHmetTCY9H1OJh3Wmfh+uI=,tag:QpAM7Z3zo13jk8lxssPjzQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:iakX9iDnw1AfqOgZd3Uj,iv:sxTd9PDKRr44rU+GxPLr5CdZHuvObw4/bxcVUXR/NPY=,tag:ZoxkwmHr93PuNpJgMeuRmQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:t6pSv5FRbAL1AzXNuydwlfPecdAYdkS6JC9dknK80K60BF0r,iv:p7/xc+Qu1UUFILVw7miyXnZQ0x2FitYuSRbeoDJlaD4=,tag:cwR3UcdJZRQI/nNYIYGJyA==,type:str]
    SECRET_CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:t+yB4tVbkARDrs1eD/lWBwTy+QlI7bTZORK3FfLg4fw=,iv:Uw1tGcXH1Evu5jhnO64db6gRwEeDH1FA5Nruy60vOl4=,tag:9EDTxKnVmitBUqX7Bk8tMA==,type:str]
    SECRET_DN: ENC[AES256_GCM,data:Sa7ww+cCiCCF/DMH,iv:KvHo3KkISNplu8RwsdwyzVlETRGnot4dAgiKIrP5r9o=,tag:axvVIH1lNIhkoHF2ecGNIw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bGpLWFlwS0JMYjk5TEVT
            Uyt5OFBjbVJxU21QVlluQktvOWZMTUFkMGg4CitMOHdTN0F4MFV5cWRWR3dXWE1o
            ckxNMzRJcDFoVGtUSldMTXpBakd6a2MKLS0tIDJUbUlRTTI3dUQ1Z1NOVjF5ZU9u
            Y1BqbHJmcENxMlJta01Vajg5eDN5djAK0z1E62xFs4uqLIKDaHkMCCtNPfa4Pb/d
            BBu7b4Cwgf0X2Md+UVFXnFj1NGpBL2rtdqMQQh1i9rXTVft6Bvj9jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-02T02:10:29Z"
    mac: ENC[AES256_GCM,data:9B71pxtBsq26vYJGr8C/kmx4mSl6afxoSPbH8c4dsw2xiQOuCUZCCUR9hAW214MQJNSpViNWtyqunnL8HBi3ZY8LvMVTRDhkWjrRrxeBfryV8CnwtRUOUAxuCB3Ya8eDHrY6imiaIQ7NNtmcmdQ8r6tnqoyabNYWwfRT/Qngw6w=,iv:r/15jLgOwu6YNZRju54kenQM0Im974Pxt6MpiIWfjJM=,tag:ge11NThjLD+ifLx02khyEQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
