apiVersion: apps/v1
kind: Deployment
metadata:
  name: factorioz
  namespace: default
  annotations:
    reloader.stakater.com/auto: "true"
    another-autoscaler/start-time: "30 01 * * 4"
    another-autoscaler/stop-time: "30 04 * * *"
spec:
  #replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: factorioz
  template:
    metadata:
      labels:
        app: factorioz
        factorio: active
    spec:
      nodeSelector:
        kubernetes.io/arch: "amd64"
      priorityClassName: high-priority
      containers:
        - name: factorioz
          image: factoriotools/factorio:1.1.104
          ports:
            - containerPort: 34197
              type: UDP
              name: game
            - containerPort: 27015
              type: TCP
              name: rcon
          envFrom:
            - configMapRef:
                name: factorioz-config
            - secretRef:
                name: factorioz-secrets
          resources:
            requests:
              cpu: "2"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "2Gi"
          volumeMounts:
            - name: data
              mountPath: /factorio
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: factorioz-data
