apiVersion: v1
kind: Secret
metadata:
    name: factorioz-secrets
    namespace: default
type: Opaque
stringData:
    USERNAME: ENC[AES256_GCM,data:5F3c,iv:kpDaO5UOZI8JYvVfpy7K5F4tvB96j8wCA5hA30BRd7c=,tag:l5Chwl5wfnSD7RYyDNBpYw==,type:str]
    TOKEN: ENC[AES256_GCM,data:BDpY50GNOHZiukq1cFjCbyihdmmQ2hUVQzlBRCay,iv:3S+Db5QWyXXVubqhxHnyAVQgfvltMbzsy1UXwdX4iGg=,tag:vKaftObKUi67WnCwCUPj6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bWpzNnVKZCttSzJSWVBp
            MGFRUXRsZFR4ZmxXd0xyd2oyWXlwYmFIUnlBCjhsOUJ3TzRhNXVoS0lIWDNWdE81
            NGJXd3ZFclhqNkc3dlpMS1pmSFQ0MEEKLS0tIEQ5K01yYlZBTlJGNEFxUC9RUVhi
            Zi9ic0Y0RDNBcDVBeTdEUU9TOWJ4Sm8KhpTCHI/fM257VMe19J5WrNZ/OgIWfyLC
            WdcRuC8+l9s/mjWsc0p4ri/v+TSfKdbWhgYtlajhcdPJyKI4WQg/9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-23T02:17:22Z"
    mac: ENC[AES256_GCM,data:RhnqLsT/dcGJKEauLHMr+4Pdj2iLKAq1/v/lVfzF1i4PI7pLSkxyBO97dCHlOouyYiV+3cieE9ZGkvLKGE9rN0iEjFA2cijjzfvhFPQ3l/od28SxhenfVh18QcAbXMDUmhYKkpyVO8B6OtZJOcz96CNBNbrDxDxDrU/HrFFttnQ=,iv:WtLWANPoA5mcO+IJqeFXzKJhb2GvB+tAHoiEiDWYipU=,tag:EY+OFPwaI9cWCWE9DP06VA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: factorioz-data-backup-config
    namespace: default
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:jngrcEURa+vRONn+Yd9aoPz5ie1nn8d008+SeAJh/zV8lwtKNWA2RLGiC1cAZKZ7Yruja2NpilzfXp44jM+Rx6Iv,iv:bkhzu5qyRPuivq11iKBWrAfQHjN76oWvNzOA3s0IQCM=,tag:lfja/c2Qb4rHbkTqTAjGUQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:aBgrfZUtOD9I/yqkTIkG+H1pxcFLJ9rKmUP5I5twSeJtlpsKrwc3MQYJEApdki2kg99cYVV3T5Ic/XECt0O0OS6qGiErEHLhxSGUHCEa90i92FKx0fE4kHcqg55LHS7x2viOu/glXhTAD+Ztz9kFwldkInXPgH8oWwgXev9joTo=,iv:NML+MR4If6GD8iPeuUTi/psnmsaARvDDYz+Y7MRUdLw=,tag:xy/OJQyXokO02UYfn9ymBA==,type:str]
    #ENC[AES256_GCM,data:XmeKYwj6ZQuykOITCYkCsXO69jLweiBytTueYnkndWDHZ9qS9VsKpdk=,iv:h/wCYTmntXVcaKXaYpSr5EiSu+Cq8va6LsL5t5P/xc0=,tag:fh4ROaeLsL8dn+dhKvG53w==,type:comment]
    #ENC[AES256_GCM,data:yMF1IblVar7KDxUpx7/UJKqSNUYncondTLlozHWXjHuMMbyg5ba1n86sltYx/RMgWUHW0ulRUE0Qj1zkACqgssIvl8qL9w==,iv:79dVKLkapWrDML/TnFcPnH56L+l41J+w0IQK3y5e7q4=,tag:Zf5oCOKpYEHsuk9CTESYmQ==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:MjVuV9A2oogytPjQ65e54dPqVhsghi3rCw==,iv:P4zKmEtKm80RZ9ZGrmzDShGM30vru8av4BocsPqwSPk=,tag:R7PZRwM1AzVqwqjJUuzhnQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:NnZniN2JZu7pNPvBuKFmEhisBRH5t8BtnwgZLzRThQ==,iv:tv1Q22LNZTqG6ZgN5ftyo11IPyFijCl0cszoBxCEc9g=,tag:j+tnVSkrPPAJZklPcm7+lQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bWpzNnVKZCttSzJSWVBp
            MGFRUXRsZFR4ZmxXd0xyd2oyWXlwYmFIUnlBCjhsOUJ3TzRhNXVoS0lIWDNWdE81
            NGJXd3ZFclhqNkc3dlpMS1pmSFQ0MEEKLS0tIEQ5K01yYlZBTlJGNEFxUC9RUVhi
            Zi9ic0Y0RDNBcDVBeTdEUU9TOWJ4Sm8KhpTCHI/fM257VMe19J5WrNZ/OgIWfyLC
            WdcRuC8+l9s/mjWsc0p4ri/v+TSfKdbWhgYtlajhcdPJyKI4WQg/9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-23T02:17:22Z"
    mac: ENC[AES256_GCM,data:RhnqLsT/dcGJKEauLHMr+4Pdj2iLKAq1/v/lVfzF1i4PI7pLSkxyBO97dCHlOouyYiV+3cieE9ZGkvLKGE9rN0iEjFA2cijjzfvhFPQ3l/od28SxhenfVh18QcAbXMDUmhYKkpyVO8B6OtZJOcz96CNBNbrDxDxDrU/HrFFttnQ=,iv:WtLWANPoA5mcO+IJqeFXzKJhb2GvB+tAHoiEiDWYipU=,tag:EY+OFPwaI9cWCWE9DP06VA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
