---
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: gateway
  namespace: networking
spec:
  selector:
    app: my-gateway-controller
  servers:
    - port:
        number: 443
        name: https
        protocol: https
      hosts:
        - "api.${SECRET_DOMAIN}"
      tls:
        mode: SIMPLE
        credentialName: "${SECRET_DOMAIN/./-}-api-tls"
