apiVersion: dbman.hef.sh/v1alpha3
kind: Database
metadata:
  name: pgadmin
  namespace: default
spec:
  credentials:
    basicAuthSecretRef: pgadmin-credentials
  databaseName: pgadmin
  databaseServerRef:
    namespace: database
    name: postgres
  prune: false
