---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  releaseName: longhorn
  interval: 30m
  chart:
    spec:
      chart: longhorn
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
      version: 1.5.1
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: true
  values:
    defaultSettings:
      backupTarget: s3://longhorn-20201224060010162400000001@us-east-2/
      backupTargetCredentialSecret: aws-secret
      defaultDataLocality: best-effort
      replicaAutoBalance: best-effort
      priorityClass: system-cluster-critical
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      mkfsExt4Parameters: -F
    persistence:
      recurringJobSelector:
        enabled: true
        jobList: '[{"name":"daily-backup", "isGroup":false}]'
    ingress:
      enabled: true
      host: longhorn.${SECRET_DOMAIN}
      annotations:
        hajimari.io/appName: "longhorn"
        hajimari.io/enable: "true"
        hajimari.io/icon: "harddisk"
