---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  releaseName: longhorn
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: longhorn
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      version: 1.6.1
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: true
  values:
    defaultSettings:
      backupTarget: s3://longhorn-20201224060010162400000001@us-east-2/
      backupTargetCredentialSecret: aws-secret
      defaultDataLocality: best-effort
      replicaAutoBalance: best-effort
      priorityClass: system-cluster-critical
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      mkfsExt4Parameters: -F
    persistence:
      recurringJobSelector:
        enabled: true
        jobList: '[{"name":"daily-backup", "isGroup":false}]'
    ingress:
      enabled: true
      host: longhorn.${SECRET_DOMAIN}
      ingressClassName: internal
      tls: true
      annotations:
        hajimari.io/appName: "longhorn"
        hajimari.io/enable: "true"
        hajimari.io/icon: "harddisk"
        nginx.ingress.kubernetes.io/auth-method: GET
        nginx.ingress.kubernetes.io/auth-url: http://authelia.default.svc.cluster.local/api/verify
        nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN}?rm=$request_method
        nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
        nginx.ingress.kubernetes.io/auth-snippet: |
          proxy_set_header X-Forwarded-Method $request_method;
    #image:
    #  longhorn:
    #    instanceManager:
    #      repository: webericjames/longhorn-instance-manager
    #      tag: c49b76187e1c80dff7dfd22e0fc980a7200fb585
