# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    namespace: database
    label:
        cnpg.io/reload: true
stringData:
    aws-access-key-id: ENC[AES256_GCM,data:5ZXFCyuSYRxdy0Mb+ZbXPQutf5U6ZB635Ng8NwSxTkc=,iv:DSzBTA5DVn0DzNATWUumSu5rhzgVeq0nh0eRjFt8HcM=,tag:HZWb1gFBVW25iF1Dgep/XA==,type:str]
    aws-secret-access-key: ENC[AES256_GCM,data:CWaaFcGLwfY1HSsUcsXg3lEca+/Z9n3MyG0jkXiKv1uc1Yt4yVkLK9lVj3n/Aqy6MJwd9s7b+Oe7QhVOsDlz4w==,iv:IDTgodMidF16JMjtWUtYOIjl7AJ+22uHa/8XzMyJ2DY=,tag:kFVhGrkM99WmIUGOeoYhUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQclpIb013bTVLSzFMRWs5
            N3FzV3ZGYjJubk1FTG1IRTBRNE03RXF4NFRrCktlejRoQmZNMEJRMlV5dUpsQmVh
            K3o2Q3BtUGkvWS93VGhITUV4bHJEd1kKLS0tIGd5ZW5zYjJCSEN2V0JubnRVcXlF
            TTUzQ1E4WW1EYndLN1NLajlZSStZY00KeNn1bSHViYJQ7rBavNF9PxysCiaNT00e
            V/+Ux5ICUl32M8dm5iIIvwmlo+8M51A+I9eTC9fy+ieTrJXDJ2ul3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-13T07:04:00Z"
    mac: ENC[AES256_GCM,data:ExLkcjYzxfOs4l4vetWSnZU7f84a+bD9BR4Rn49wNv8lazwJIju6s7lN/2QeWBYglCbY9Of/osnosQn0j1AGMvss0dWu3MoVtQL1dNlgOM678zywbwvVaS3jYNGCqsYKVfupwmolY4Ia87KHIJoDVIP9Z0vCWWYSVB+DZ2lN4sE=,iv:oKedtqC0Pdlypu6Bohb7gbxoGc7NhjzwTlZKF9WTuz8=,tag:yQLZNIOIvlpwTky/+fMXng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
# yamllint disable
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: superuser-secret
    namespace: database
stringData:
    username: ENC[AES256_GCM,data:vKstJGjC0A==,iv:7lLHczoFKkPYMT4dC8mIjtunXK+xTmc58L9BZ6dYFFU=,tag:MsogLVbkL7OVa/p7ue14vw==,type:str]
    password: ENC[AES256_GCM,data:cxGmfX6Z4W6ohmTZMv4kOMy92iZbHbWvfFR9BFd4fF8=,iv:qldJfe5xGqOm8RjorSC+osNKQSWvKShgQGOh3ne3xnk=,tag:o5azT/3dIi5Nb6MdrIvitw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQclpIb013bTVLSzFMRWs5
            N3FzV3ZGYjJubk1FTG1IRTBRNE03RXF4NFRrCktlejRoQmZNMEJRMlV5dUpsQmVh
            K3o2Q3BtUGkvWS93VGhITUV4bHJEd1kKLS0tIGd5ZW5zYjJCSEN2V0JubnRVcXlF
            TTUzQ1E4WW1EYndLN1NLajlZSStZY00KeNn1bSHViYJQ7rBavNF9PxysCiaNT00e
            V/+Ux5ICUl32M8dm5iIIvwmlo+8M51A+I9eTC9fy+ieTrJXDJ2ul3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-13T07:04:00Z"
    mac: ENC[AES256_GCM,data:ExLkcjYzxfOs4l4vetWSnZU7f84a+bD9BR4Rn49wNv8lazwJIju6s7lN/2QeWBYglCbY9Of/osnosQn0j1AGMvss0dWu3MoVtQL1dNlgOM678zywbwvVaS3jYNGCqsYKVfupwmolY4Ia87KHIJoDVIP9Z0vCWWYSVB+DZ2lN4sE=,iv:oKedtqC0Pdlypu6Bohb7gbxoGc7NhjzwTlZKF9WTuz8=,tag:yQLZNIOIvlpwTky/+fMXng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
