# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    namespace: database
stringData:
    aws-access-key-id: ENC[AES256_GCM,data:5ZXFCyuSYRxdy0Mb+ZbXPQutf5U6ZB635Ng8NwSxTkc=,iv:DSzBTA5DVn0DzNATWUumSu5rhzgVeq0nh0eRjFt8HcM=,tag:HZWb1gFBVW25iF1Dgep/XA==,type:str]
    aws-secret-access-key: ENC[AES256_GCM,data:6ocLiwIDgQrxOr0le1ozM6YwZdynx0lzv7+PiUbiy2OydcyHyZerZrURUjc2BpYLuAko1rnXE5wCe9t9pfCwWg==,iv:1XYqEUTuSljgP/jBsDz5fbBuuwdZi0RMaz5pIwtl+/M=,tag:5sKyeQ2VRL4+n7dKReeFEg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQclpIb013bTVLSzFMRWs5
            N3FzV3ZGYjJubk1FTG1IRTBRNE03RXF4NFRrCktlejRoQmZNMEJRMlV5dUpsQmVh
            K3o2Q3BtUGkvWS93VGhITUV4bHJEd1kKLS0tIGd5ZW5zYjJCSEN2V0JubnRVcXlF
            TTUzQ1E4WW1EYndLN1NLajlZSStZY00KeNn1bSHViYJQ7rBavNF9PxysCiaNT00e
            V/+Ux5ICUl32M8dm5iIIvwmlo+8M51A+I9eTC9fy+ieTrJXDJ2ul3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-13T06:22:58Z"
    mac: ENC[AES256_GCM,data:YrVLKkXkSdqkOkdXAuKNWsB4QnwY2hWH1hGi5aW59p4Gq99JbhlkYcl6tcGa9bKO2UP3kQ2r922b1ETHkY8JJZjFkBI2hcABlRWVuwDyywKGeJaym1mOpGkVB04t8mUyKnB50nL979f4hGT6tKV8pCW3Ya6AfIBiJ87T0rbHaYs=,iv:fDjPYOEuhl76M6Zxln8Q7oXCQ54Y48qwn0MtE0JpEAY=,tag:iUja0xXHaeGJdtF1leHlJg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
# yamllint disable
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: superuser-secret
    namespace: database
stringData:
    username: ENC[AES256_GCM,data:vKstJGjC0A==,iv:7lLHczoFKkPYMT4dC8mIjtunXK+xTmc58L9BZ6dYFFU=,tag:MsogLVbkL7OVa/p7ue14vw==,type:str]
    password: ENC[AES256_GCM,data:cxGmfX6Z4W6ohmTZMv4kOMy92iZbHbWvfFR9BFd4fF8=,iv:qldJfe5xGqOm8RjorSC+osNKQSWvKShgQGOh3ne3xnk=,tag:o5azT/3dIi5Nb6MdrIvitw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQclpIb013bTVLSzFMRWs5
            N3FzV3ZGYjJubk1FTG1IRTBRNE03RXF4NFRrCktlejRoQmZNMEJRMlV5dUpsQmVh
            K3o2Q3BtUGkvWS93VGhITUV4bHJEd1kKLS0tIGd5ZW5zYjJCSEN2V0JubnRVcXlF
            TTUzQ1E4WW1EYndLN1NLajlZSStZY00KeNn1bSHViYJQ7rBavNF9PxysCiaNT00e
            V/+Ux5ICUl32M8dm5iIIvwmlo+8M51A+I9eTC9fy+ieTrJXDJ2ul3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-13T06:22:58Z"
    mac: ENC[AES256_GCM,data:YrVLKkXkSdqkOkdXAuKNWsB4QnwY2hWH1hGi5aW59p4Gq99JbhlkYcl6tcGa9bKO2UP3kQ2r922b1ETHkY8JJZjFkBI2hcABlRWVuwDyywKGeJaym1mOpGkVB04t8mUyKnB50nL979f4hGT6tKV8pCW3Ya6AfIBiJ87T0rbHaYs=,iv:fDjPYOEuhl76M6Zxln8Q7oXCQ54Y48qwn0MtE0JpEAY=,tag:iUja0xXHaeGJdtF1leHlJg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
