---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
          nodeSelector:
            feature.node.kubernetes.io/usb-02_1a86_55d4.present: "true"
        containers:
          main:
            image:
              repository: ghcr.io/koenkk/zigbee2mqtt
              tag: 1.33.2
            env:
              ZIGBEE2MQTT_DATA: /data
              ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_LEVEL: debug
              ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_OUTPUT: '["console"]'
              #ZIGBEE2MQTT_CONFIG_FRONTEND_PORT: &port 80
              ZIGBEE2MQTT_CONFIG_FRONTEND_URL: https://zigbee2mqtt.${SECRET_DOMAIN}
            resources:
              requests:
                cpu: 10m
                memory: 128M
              limits:
                memory: 256M
    persistence:
      data:
        enabled: true
        mountPath: /data
        accessMode: ReadWriteOnce
        type: persistentVolumeClaim
        size: 1Gi
        storageClass: longhorn
      usb:
        type: hostPath
        hostPath: /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230525162016-if00
        hostPathType: CharDevice
        globalMounts:
          - path: /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230525162016-if00
    service:
      main:
        ports:
          http:
            port: 8080

    ingress:
      main:
        enabled: true
        className: internal
        hosts:
          - host: &host "zigbee2mqtt.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
