apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-secret
    namespace: default
stringData:
    network_key: ENC[AES256_GCM,data:rc3iBAKkbytUF0y5wZX42g13E2bi3Plih4ie0aw1LJMvwsuppj3EmNhpMOHXa7Kn1fMhRPA1NWaFnGy9OA53EsMgrc6ksDv9,iv:otkBQ92Xux/sSeZJhe9c4eHQ6ZWzN4y/opWhAFKcMxU=,tag:qn9/l8cWAUEids4ygm9AFA==,type:str]
    pan_id: ENC[AES256_GCM,data:wGC8hTU=,iv:dNWqnnAQ0GsthXPPWwFh3/ur0QxAhsydby4XA1SV448=,tag:ymag+k68zEvArFI3+vkp/w==,type:str]
    ext_pan_id: ENC[AES256_GCM,data:7Z/F/oPpvo8LwGQItF9/+M4G9kXbJsTWR/Hvu5OHbrrA4AXi,iv:ABt2XmbLIaE3vYqK+NkdoqstVSD6AhvBLpohvb5tCHw=,tag:SMhjCjk+Il3PwmTexhi0HQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnRzNrbzQ0TFMrSnhseUpV
            dVNCTGxpOHBoK2MxbTgwYW9xZmZWVWltdUJnCnUrTUdROFRGUEF6ZEpwMEhhMXRX
            Q0lkTWhkdytPVEFOd3RPQ2tvdVFwWWMKLS0tIDN3LzFhWkR0S3JVbVd1WkRHL1BR
            UEpaUVAxVEJESVJWSUkvMTQrMllaV3cKrwTrrGPW7U95VJUVTwx0tEkJNhZRx6pX
            X3pLE0+xkX6tGcsNTc/IEwaMM1hUDFjzMTjKHxYCLtt/ysgX1P+Bow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-11T22:45:26Z"
    mac: ENC[AES256_GCM,data:osWLE3kPMnIlmvFgj0kqkLtVDbPnXl6XTv4HzGR+5vhPxohbn3uTKWyWhA/1ObTm2sr7TleFIXVNlpXg2LskelK5oOPDsvsCO1G6JV+QYn76NzF9HoYj+sLyUcKf/vwMoCUmpggOgil2znQi46cZDetNkjhdT6cB2G17SQ+qO/U=,iv:wAn7JJkyFWlbyjVBPiHbcamduNCgaDD8x1nYqRDgRPo=,tag:YJoxMkrt24+IRCTjpj0oTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-data-backup-config
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:oTxxRcmWjeiTeYo2MysvfRU7vYz27YdeaI4vLNqgfymYXLNil6PpFBiuK1x8lqClyGSmYBKp62Wle+YHYwlZ0nDPffi7,iv:XrSDqBwqx8f4Jf1393WE8HOEDOUtb9vYnaa0hrxAki4=,tag:j4orPOWEkxzS4TDwfFMrxw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:D8qcUiXmhXejPj69BETYCCinID71LL1fDd9wtGn9Sa/IPyQvFUdv+HD3cisjlALp7Ny1BUX/y3gLhveUOneY9AE/vjcbHi+oWGzEDdbOzO5QNoB42LgSm5PFWcRhp1GYdeRrU63DJwIS63RhY910bTBaglag2FeM7OP0+widoGA=,iv:ID8XB+4neAE90CsrLVzGUzDSgye0DXjmEfBcz2+8A0I=,tag:xBbmxSjJzg8oz8wq7LeHCA==,type:str]
    #ENC[AES256_GCM,data:1igegn3ynUKc++YFW5fTnNFxdbwAIpg/4++D7yHomfOwq00Ni3+N9Yo=,iv:ILByXPfmfC1nTSmUrEoNFqa5yxXn/oyaDW2EGTagCDk=,tag:NWj+HJlBwXJe3fXts0N96Q==,type:comment]
    #ENC[AES256_GCM,data:Rkao5ThUEjicGhgn+FKOrIk1i/WE6yyOeFukDsU4hvKNSFUL2crh8KyCHt6n/huci6J3dIdAI4op1+KsqR4nzhBOQabM3A==,iv:SjxbmIfKpu1OYXaGJWIqZL0rwDyuogJEp2bBlH5zSHA=,tag:TePee3nJiBv5r/69i/2rxA==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:6Sk5t5nM8+3YSxi342faspiit1WA2ryL5w==,iv:DLUIF560TkQwvcCLEl0e+l5vsZiAcRAiLUxMyt2uqtY=,tag:mOV65JTyybpLDz2DsmAbWQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:lqNtMwiBgvhAdNLVIs3VHb44f3EpZqoyoODIz9lF7A==,iv:aj3oaRCtP7P0SpB+umxpiPzxmtYTfT9187qUcKgrtSk=,tag:EaJIu525eMsS1ncdbr/N9w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnRzNrbzQ0TFMrSnhseUpV
            dVNCTGxpOHBoK2MxbTgwYW9xZmZWVWltdUJnCnUrTUdROFRGUEF6ZEpwMEhhMXRX
            Q0lkTWhkdytPVEFOd3RPQ2tvdVFwWWMKLS0tIDN3LzFhWkR0S3JVbVd1WkRHL1BR
            UEpaUVAxVEJESVJWSUkvMTQrMllaV3cKrwTrrGPW7U95VJUVTwx0tEkJNhZRx6pX
            X3pLE0+xkX6tGcsNTc/IEwaMM1hUDFjzMTjKHxYCLtt/ysgX1P+Bow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-11T22:45:26Z"
    mac: ENC[AES256_GCM,data:osWLE3kPMnIlmvFgj0kqkLtVDbPnXl6XTv4HzGR+5vhPxohbn3uTKWyWhA/1ObTm2sr7TleFIXVNlpXg2LskelK5oOPDsvsCO1G6JV+QYn76NzF9HoYj+sLyUcKf/vwMoCUmpggOgil2znQi46cZDetNkjhdT6cB2G17SQ+qO/U=,iv:wAn7JJkyFWlbyjVBPiHbcamduNCgaDD8x1nYqRDgRPo=,tag:YJoxMkrt24+IRCTjpj0oTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
