apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alert.yaml
  - ingress.yaml
  - pod-monitor.yaml
  - prometheus-rule.yaml
  - provider.yaml
  - receiver.yaml
  - secret.sops.yaml
