---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: goldilocks
      sourceRef:
        kind: HelmRepository
        name: fairwinds-charts
        namespace: flux-system
  values:
    dashboard:
      ingress:
        enabled: false
        annotations:
          hajimari.io/appName: "goldilocks"
          hajimari.io/enable: "true"
          hajimari.io/icon: "scale-unbalanced"
        hosts:
          - host: goldilocks.hef.sh
            paths:
              - path: /
                pathType: Prefix
