apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hass-config
  namespace: default
spec:
  storageClassName: longhorn
  dataSourceRef:
    apiGroup: volsync.backube
    kind: ReplicationDestination
    name: hass-config
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
