---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: immich
      version: 0.7.2
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
      interval: 5m
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    immich:
      persistence:
        library:
          existingClaim: immich
