---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: immich
      version: 0.8.2
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
      interval: 5m
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    env:
      #REDIS_HOSTNAME: redis.database.svc.cluster.local
      DB_HOSTNAME: postgres-rw.database.svc.cluster.local
      DB_USERNAME:
        valueFrom:
          secretKeyRef:
            name: immich-credentials
            key: username
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: immich-credentials
            key: password
      DB_DATABASE_NAME: immich
      DB_VECTOR_EXTENSION: pgvector
    image:
      tag: v1.115.0
    immich:
      persistence:
        library:
          existingClaim: immich
    redis:
      enabled: true
    server:
      ingress:
        main:
          enabled: true
          hosts:
            - host: immich.${SECRET_DOMAIN}
              paths:
                - path: "/"
