---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          nodeSelector:
            feature.node.kubernetes.io/usb-02_1a86_55d4.present: "true"
        containers:
          main:
            image:
              repository: ghcr.io/koenkk/zigbee2mqtt
              tag: 1.37.1
            env:
              TZ: ${SECRET_TZ}
              ZIGBEE2MQTT_DATA: /data
              # [random.randint(0,255) for _ in range(8)]
              ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID:
                valueFrom:
                  secretKeyRef:
                    name: zigbee2mqtt-secret
                    key: ext_pan_id
              ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_DISCOVERY_TOPIC: homeassistant
              ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_LEGACY_ENTITY_ATTRIBUTES: "false"
              ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_LEGACY_TRIGGERS: "false"
              ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_STATUS_TOPIC: homeassistant/status
              ZIGBEE2MQTT_CONFIG_ADVANCED_LAST_SEEN: ISO_8601
              ZIGBEE2MQTT_CONFIG_ADVANCED_LEGACY_API: "false"
              ZIGBEE2MQTT_CONFIG_ADVANCED_LEGACY_AVAILABILITY_PAYLOAD: "false"
              ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_LEVEL: info
              # [random.randint(0,255) for _ in range(16)]
              ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY:
                valueFrom:
                  secretKeyRef:
                    name: zigbee2mqtt-secret
                    key: network_key
              ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_OUTPUT: '["console"]'
              # random.randint(1,0xffff-1)
              ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID:
                valueFrom:
                  secretKeyRef:
                    name: zigbee2mqtt-secret
                    key: pan_id
              ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_LEGACY: "false"
              ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_RETAIN: "true"
              ZIGBEE2MQTT_CONFIG_EXPERIMENTAL_NEW_API: "true"
              ZIGBEE2MQTT_CONFIG_FRONTEND: '{}' # workaround for a bug, frontend is 'true' by default, not an object
              #ZIGBEE2MQTT_CONFIG_FRONTEND_PORT: &port 8080
              ZIGBEE2MQTT_CONFIG_FRONTEND_URL: https://zigbee2mqtt.${SECRET_DOMAIN}
              ZIGBEE2MQTT_CONFIG_HOMEASSISTANT: "true"
              ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC: zigbee2mqtt
              ZIGBEE2MQTT_CONFIG_MQTT_INCLUDE_DEVICE_INFORMATION: "true"
              ZIGBEE2MQTT_CONFIG_MQTT_REJECT_UNAUTHORIZED: "true"
              ZIGBEE2MQTT_CONFIG_MQTT_SERVER: "mqtt://mosquitto.default.svc.cluster.local"
              ZIGBEE2MQTT_CONFIG_MQTT_USER:
                valueFrom:
                  secretKeyRef:
                    name: mosquitto-secret
                    key: zigbee2mqtt_user
              ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: mosquitto-secret
                    key: zigbee2mqtt_password
              ZIGBEE2MQTT_CONFIG_PERMIT_JOIN: "false"
              # thank you /u/asinla1 https://www.reddit.com/r/homeassistant/comments/16j2k00/sonoff_zigbee_usb_differences/k0nob6w/
              ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER: ezsp
              ZIGBEE2MQTT_CONFIG_SERIAL_PORT: /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230525162016-if00


            securityContext:
              privileged: true
            resources:
              requests:
                memory: 128M
              limits:
                memory: 256M
    persistence:
      data:
        enabled: true
        existingClaim: zigbee2mqtt-data
        mountPath: /data
      usb:
        type: hostPath
        # I have the "ZDongle-E" version of the zigbee USB Dongle Plus, not the original
        # I need a different set of tools/firmware from most of the docs I found for the original version.
        # https://github.com/Elelabs/elelabs-zigbee-ezsp-utility
        # https://github.com/xsp1989/zigbeeFirmware/blob/master/firmware/Zigbee3.0_Dongle-NoSigned/EZSP/ncp-uart-sw_6.10.3_115200.gbl
        # I sort of tried newer versions of the gbl, but I had enough trouble gettings that when they started working,
        # I stopped messing with the firmware.
        hostPath: /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230525162016-if00
        hostPathType: CharDevice
        globalMounts:
          - path: /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230525162016-if00
    service:
      main:
        ports:
          http:
            port: 8080

    ingress:
      main:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/auth-method: GET
          nginx.ingress.kubernetes.io/auth-url: http://authelia.default.svc.cluster.local/api/verify
          nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN}?rm=$request_method
          nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
          nginx.ingress.kubernetes.io/auth-snippet: |
            proxy_set_header X-Forwarded-Method $request_method;
        className: internal
        hosts:
          - host: &host "zigbee2mqtt.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
