---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  interval: 5m
  chart:
    spec:
      chart: gitea
      sourceRef:
        kind: HelmRepository
        name: gitea-charts
        namespace: flux-system
  values:
    ingress:
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/icon: "git"
      enabled: true
      hosts:
        - host: git.hef.sh
          pahts:
            - path: /
              pathType: Prefix
