apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-storage
  namespace: gitea
spec:
  volumeName: "gitea-storage:nam"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-static

