apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-storage
  namespace: gitea
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  #storageClassName: longhorn-static
