apiVersion: v1
kind: Secret
metadata:
    name: gitea-secrets
    namespace: gitea
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:yV4IUowXuriRNN0K3gejtIO8Tropz8dO3nO4YNbSxes1jTRAPlf+OD/cHRpPzovWfYc+T+gsLvTMoBT8ttnXvh8xrRenOuqsC0zguZ4fZTQrXYKXvBPSaxQarK6+wfjj5TdNFg==,iv:K+ll+Yo29C79BfMpIIfJ0RRK/OkkFKqCoGStQYr9QE4=,tag:OMbqF8+99D+A0lQRkAaOPA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4cDdRc1hQTGo0eGNwb3Jh
            WE9kZ2t2WEZJRXpDcUpjVFpKWEpJSTBSQWtzCnRIOWdQSFhvcFQwWDlsZHV0V0FW
            YmNDeWZ6aWRqeTJKZHp5WGkyQ25iWUkKLS0tIFBxZGNIaUpFSFlsUFQ1TmJkVW5y
            d0VIT3FoSGpEZ0F1RFd1ZE5IcTAyRUEK60/Gx93iRa7fjV7pfaBQ5au9dezYjIS5
            B0EeRknpM2sGEv0RHTIu5nohJGiEJHWtTlyLQLldzkQykCQLXv6KBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-20T16:04:25Z"
    mac: ENC[AES256_GCM,data:glJgw6f6CyY0XU+A66T/OpHK5BHbHC3OcxM7yeh8z8Sv9nY3CIdTaPrVtMrcMrLQ5VD6KVro8JNnB49FzLHyro8JgV4S5xT7e8UEJDWqZICsza3X7t0IGIIRPWHQe+gpdq0zL4xL1N8ULKTdZYyvIvte3HaabKf/IeBcri3oTRQ=,iv:dQ7Avm8v+syLUfZV5sT6USOdkhiaJWw/6r3DNpXc5BE=,tag:oGy86rRRaSG/vsEtp+LUJg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
