apiVersion: v1
kind: Secret
metadata:
    name: gitea-secrets
    namespace: gitea
type: Opaque
data:
    SECRET_KEY: ENC[AES256_GCM,data:3ZQ0PFuQwY1gjFdz9ve/qSpIFuNHCZPJ1j3z0ZURbPC6QRydoMiYACvrFnOOwLv1KPALiVCCPXZy+K1pQ7YCpcDLfKiPXI+MHEhPInQZZHLX2OdNJrHKr8ZzOTa0BOjaGg/E/g==,iv:kqCclffcwW+6AfCWHp+bQgA0nORMK/ND5WE7XU1XKI8=,tag:JID9crACbiL+Klou3qSjig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4cDdRc1hQTGo0eGNwb3Jh
            WE9kZ2t2WEZJRXpDcUpjVFpKWEpJSTBSQWtzCnRIOWdQSFhvcFQwWDlsZHV0V0FW
            YmNDeWZ6aWRqeTJKZHp5WGkyQ25iWUkKLS0tIFBxZGNIaUpFSFlsUFQ1TmJkVW5y
            d0VIT3FoSGpEZ0F1RFd1ZE5IcTAyRUEK60/Gx93iRa7fjV7pfaBQ5au9dezYjIS5
            B0EeRknpM2sGEv0RHTIu5nohJGiEJHWtTlyLQLldzkQykCQLXv6KBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-20T15:48:39Z"
    mac: ENC[AES256_GCM,data:z31gkRCvGeszuReDFTJw6hMoQ5WSCp6l81YMTpSR1DfopRUK4yjSU3I0PSQyRld4Q3d+6bv2xS4oDKGQ3unA0Z4KvgeZlDLRTlmsGxpqzRzRC6EXfNgS/I0HB3Z/Dy1eCiRQLu3H/3Q9kFXhCybrTy4ejtfETJF34F1gSSJwZbk=,iv:75YBmw9QkE/P7E1kO78isDPoOwjBdqlZeqLAki/TIRs=,tag:wyV9LxI2uDDdNd7GfI2L/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
