apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-configmap
  namespace: default
data:
  configuration.yaml: |
    ---
    session:
      cookies:
        - domain: "${SECRET_DOMAIN}"
          name: authelia_session
          secure: true
          http_only: true
          same_site: strict
          expiration: 3600
