apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-configmap
  namespace: default
data:
  configuration.yaml: |
    ---
    session:
      cookies:
        - domain: ${SECRET_DOMAIN}
          authelia_url: https://auth.${SECRET_DOMAIN}
          name: authelia_session
          same_site: lax
    storage:
      local:
        path: /data/db.sqlite3
