apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-configmap
  namespace: default
data:
  configuration.yaml: |
    ---
    authentication_backend:
      ldap:
        address: ldap://lldap.default.svc.cluster.local:389
        base_dn: ${SECRET_DN}
        additional_users_dn: ou=People
        users_filter: (&({username_attribute}={input})(objectClass=person))
        additional_groups_dn: ou=groups
        groups_filter: (member={dn})
        group_search_mode: filter
        user: uid=admin,ou=people,${SECRET_DN}
        attributes:
          username: uid
          display_name: displayName
          mail: mail
          member_of: memberOf
          group_name: cn
    session:
      same_site: lax
      inactivity: 5m
      expiration: 1h
      remember_me: 1M
      cookies:
        - domain: ${SECRET_DOMAIN}
          authelia_url: https://auth.${SECRET_DOMAIN}
          name: authelia_session
          same_site: lax
      redis:
        host: redis.database.svc.cluster.local
        database_index: 14
        high_availability:
          sentinel_name: redis-master
          nodes:
            - host: redis-node-0.redis-headless.database.svc.cluster.local
              port: 26379
            - host: redis-node-1.redis-headless.database.svc.cluster.local
              port: 26379
            - host: redis-node-2.redis-headless.database.svc.cluster.local
              port: 26379

    storage:
      postgres:
        address: postgres-rw.database.svc.cluster.local
        database: authelia
        username: authelia
    access_control:
      default_policy: two_factor
      networks:
        - name: internal
          networks:
          - "10.0.0.0/8"
          - "192.168.0.0/16"

    notifier:
      disable_startup_check: true
      smtp:
        address: smtp-relay.default.svc.cluster.local:25
        sender: Authelia <authelia@${SECRET_DOMAIN}>
        disable_require_tls: true
    totp:
      disable: false
      issuer: ${SECRET_DOMAIN}
      algorithm: sha512
      digits: 8
