apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-configmap
  namespace: default
data:
  configuration.yaml: |
    ---
    session:
      cookies:
        - domain: "${SECRET_DOMAIN}"
          authelia_domain: https://auth.${SECRET_DOMAIN}
          name: authelia_session
          secure: true
          same_site: lax
