apiVersion: dbman.hef.sh/v1alpha3
kind: Database
metadata:
  name: authelia
  namespace: default
spec:
  credentials:
    basicAuthSecretRef: authelia-credentials
  databaseName: authelia
  databaseServerRef:
    namespace: database
    name: postgres
