apiVersion: v1
kind: Secret
metadata:
    name: authelia-secret
    namespace: default
stringData:
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:0BPhlQvEeEST6IO4zNQnR1K1LdUFNmmQsfhUi66xw+8=,iv:0xKOb37hCVOJp8dEShE5Ll/VSDHpyoE1jEw+yJ7vW68=,tag:Ya64o7ayY6jw2e1fn3SGCw==,type:str]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:bVhLmxtEVvTXV/tr2PR9TWC134S5o+HMVM9MTZ//cc4=,iv:pIvlMzFj7AhjbJ/n0BMhC/48A4imvn9udQy8Zs0R+T0=,tag:2lLFudgEhPJGs+Cl7cZxsg==,type:str]
