apiVersion: v1
kind: Secret
metadata:
    name: authelia-secret
    namespace: default
stringData:
    AUTHELIA_JWT_SECRET: ENC[AES256_GCM,data:OPdw6bK09aA3rl49QjEnKWbNXa6lT+tn9sp5UoSjg2/inDO0QvVPSaO4WxTHsfBq93Cnelw3azW/T1YWsgQBpQK/NQmQ1sZnuAxttqCglVM=,iv:QFmQywpNBaFvcFf846iNqguaNBVCLaapLYzqyO2rDmI=,tag:L8oFd2P8qkaehbGfDjvQGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4OHFYY2thWVV2SFRpUk1Z
            OFBScUVrbkdyTFhLTVZaeGZPUFNDcTdvdUFRClBmTm5JSlRZc2ttT1h2ZUh4N204
            eTBILzVCRklSdkVBdDJIajQwOVZpalEKLS0tIGg1eTFrQlJyaGtZT29SOXJNZWFU
            blUvRXA4TEYwVE1LM2k4dnBsbDZUQ1kKWEaNb+h751KW4U/uzYrBj6hyzUwb2DNy
            BrCc6VfXLZyTYm7snJAUIq1N8njd/YEyrCS9iZhN3DNpE83T0t6u7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-20T03:40:03Z"
    mac: ENC[AES256_GCM,data:k4euDI1jEpMSwSa0x/1IZeGaaiVO9/erpCpmBB8GVXJM0Gm6oHrWZDc+srynALQPkHIDQGqPUtfkbWzQGMpCqv411XriruzTmiLhNdHRNfSUJkYhi+CpR4yHq3h1maMuudEGhbeqmc5zE9zk36SVE3qKvHMgaL3mLh2+9IpbTzU=,iv:U4TKwg2OoG4CIGqB5B145qieg1jW0k77ot+b6f62QQg=,tag:jjARwc08d77YTjs3aRgk3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
