apiVersion: v1
kind: Secret
metadata:
    name: authelia-secret
    namespace: default
stringData:
    AUTHELIA_JWT_SECRET: ENC[AES256_GCM,data:OPdw6bK09aA3rl49QjEnKWbNXa6lT+tn9sp5UoSjg2/inDO0QvVPSaO4WxTHsfBq93Cnelw3azW/T1YWsgQBpQK/NQmQ1sZnuAxttqCglVM=,iv:QFmQywpNBaFvcFf846iNqguaNBVCLaapLYzqyO2rDmI=,tag:L8oFd2P8qkaehbGfDjvQGg==,type:str]
    AUTHELIA_STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:sClAtBf5EBxFIvSYMdXTs7N1gFFtrZYVyNZq+tzhze5tZZuvmsTSwrc43bSquNLEUjmuUbqIP1gXa7tQequYdp96DMw+9rwMr78YZSWUkMc=,iv:r9ZXDixheiAAIgrseqjQzeTCGzOjEZSMAZeP9WJzyiI=,tag:Ngl23TpFHgsbhZRptN2naA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4OHFYY2thWVV2SFRpUk1Z
            OFBScUVrbkdyTFhLTVZaeGZPUFNDcTdvdUFRClBmTm5JSlRZc2ttT1h2ZUh4N204
            eTBILzVCRklSdkVBdDJIajQwOVZpalEKLS0tIGg1eTFrQlJyaGtZT29SOXJNZWFU
            blUvRXA4TEYwVE1LM2k4dnBsbDZUQ1kKWEaNb+h751KW4U/uzYrBj6hyzUwb2DNy
            BrCc6VfXLZyTYm7snJAUIq1N8njd/YEyrCS9iZhN3DNpE83T0t6u7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-20T07:29:54Z"
    mac: ENC[AES256_GCM,data:PVxoNDV5U9x7zpHGcbtVYQoWWIOCQM7ZCNFbokfRRU7gCPO/oLxCfbAJ8rqu3YC3qfvs4sWUgSEAHuX2KIbz5tdMwqEjmhRh8bZEUCXODHQqod1lCgnNxYyMrBKtjJOPbozm5+ek+a21WPLVkhy413ZcmqvNoGLEFNlOHEJNbY0=,iv:4Sro6ZqPu7doGSc+LXOi6zIumwaSacQ13FeyPok/yt0=,tag:5m53nTy0YdCEMO5XtdqkGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
