---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: vpa
spec:
  interval: 10m
  chart:
    spec:
      chart: vpa
      sourceRef:
        kind: HelmRepository
        name: fairwinds-charts
        namespace: flux-system
  values:
    prometheus-address: http://prometheus-prometheus.monitoring.svc.cluster.local:9090
    storage: prometheus