---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - database
  - default
  - flux-system
  - longhorn
  - minio/ks.yaml
  - networking
  - observability
  - system-upgrade
