apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  dataSourceRef:
    apiGroup: volsync.backube
    kind: ReplicationDestination
    name: test-data
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
