apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: test-data
  namespace: default
spec:
  trigger:
    manual: restore-once
  restic:
    repository: restic-config
    copyMethod: Snapshot
    volumeSnapshotClassName: longhorn
    storageClassName: longhorn
    # hacks
    accessModes: ["ReadWriteOnce"]
    capacity: 8Gi
