---
# k8s service file
apiVersion: v1
kind: Service
metadata:
  name: volsync
  namespace: default
spec:
  selector:
    app: volsync
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
