apiVersion: v1
kind: Secret
metadata:
    name: credentials
    namespace: external-dns
data:
    aws_access_key_id: ENC[AES256_GCM,data:4Q+4rd0jtrxbqnkD6KdxFHBjI0o=,iv:t0Ac1tmKgDh8H14IjKQIqn3x+QIOqu9ilnV5ws/fN+o=,tag:TinblAMX4VxSc/d6Lg43gw==,type:str]
    aws_secret_access_key: ENC[AES256_GCM,data:lvHGgG6paEKmErpzD4HGzC0wb7iHL4HM77Pq4omWkbrUnsM1kQjifw==,iv:UxCmohB04GISzy6d3UW/xzTJdst+lF0qqcleiDdJDqA=,tag:HDVSgCMDBc+ViFBnjgAn5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZGxMajg5Tmt3c3RpMUdY
            WEJLSGNDZytYanBWTE9IbUUySVBVQ3E1MENrCkdoUDF0aVVheGNEdzNuRE5Jd3JV
            N3Jpc29MSDZ2NWUwM2srY0FZZTdmWDgKLS0tIGtIeStSTmZMTEJKc3VhTWxwUnVw
            cXozTUpkQ25KMWx2U3BnMEJ5U0JEOGcKNbD64uaT3LSis7q2ddLJvsNk0GHHfUFi
            pinsHMQbISN2x2VjSvMOl0gUL47dHOBPnO6hV0wjdxLcgLib6zahKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-19T20:00:42Z"
    mac: ENC[AES256_GCM,data:F+7F5Hcse8yFVQUzOLBumtNKR+s/NflWqbRnNg4y3vfEmVc37/ry2L62j8Kbuo3Dq0akXHtOulv2oHns5RBKq4SHqYOY6M2YLcYPD4OaNN07IWN8lPNZ1g5+VdKEwNMmc8n2IGKE1Z+hEE2dC6FFecQ+y5LA+UggOz5ntnKG3DM=,iv:D/8qgOGkucKib5+XYv0t+akFO95FQLlr/o+f4TF6JMs=,tag:IVdVwiXoR0S0tUYURfLzcw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
