---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 5m
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: external-dns-charts
        namespace: flux-system
  values:
    env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            key: aws_access_key_id
            name: credentials
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            key: aws_secret_access_key
            name: credentials
      - name: AWS_REGION
        value: us-east-2
    sources:
      - service
      - ingress
      #- istio-gateway
      #- istio-virtualservice
    provider: aws
    domainFilters:
      - hef.sh
    policy: sync
    txtOwnerId: external-dns
    extraArgs:
      - --aws-zone-type=public
      - --aws-zone-tags=use=external-dns
