---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: gitea
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: gitea
      version: 9.6.1
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      rootless: true
    redis-cluster:
      enabled: false
    postgresql:
      enabled: false
    postgresql-ha:
      enabled: false
    ingress:
      enabled: true
      className: internal
      hosts:
        - host: git.${SECRET_DOMAIN}
    gitea:
      #additionalConfigSources:
      #  - configMap:
      #      name: gitea-config
      #  - secret:
      #      name: gitea-secrets
      additionalConfigFromEnvs:
        - name: GITEA__DATABASE__PASSWD
          valueFrom:
            secretKeyRef:
              name: gitea-credentials
              key: password
      admin:
        existingSecret: gitea-admin-secret
      oauth:
        - name: "auth.${SECRET_DOMAIN}"
          existingSecret: gitea-oauth-secret
          provider: "openidConnect"
          autoDiscoverUrl: https://auth.${SECRET_DOMAIN}/.well-known/openid-configuration
      persistence:
        enabled: false
      config:
        database:
          DB_TYPE: postgres
          HOST: postgres-rw.database.svc.cluster.local:5432
          NAME: gitea
          USER: gitea
        session:
          provider: db.yaml
        cache:
          ADAPTER: redis
          HOST: redis://redis.database.svc.cluster.local:6379/0?pool_size=100&idle_timeout=180s
        queue:
          TYPE: redis
          CONN_STR: redis://redis.database.svc.cluster.local:6379
        indexer:
          ISSUE_INDEXER_TYPE: bleve
          REPO_INDEXER_ENABLED: true
        mailer:
          ENABLED: true
          PROTOCOL: smtp
          SMTP_ADDR: smtp-relay.default.svc.cluster.local
          SMTP_PORT: 25
          FROM: gitea <gitea@${SECRET_DOMAIN}>
