apiVersion: v1
kind: Secret
metadata:
    name: gitea-secrets
    namespace: default
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:yV4IUowXuriRNN0K3gejtIO8Tropz8dO3nO4YNbSxes1jTRAPlf+OD/cHRpPzovWfYc+T+gsLvTMoBT8ttnXvh8xrRenOuqsC0zguZ4fZTQrXYKXvBPSaxQarK6+wfjj5TdNFg==,iv:K+ll+Yo29C79BfMpIIfJ0RRK/OkkFKqCoGStQYr9QE4=,tag:OMbqF8+99D+A0lQRkAaOPA==,type:str]
    GITEA__database__PASSWD: ENC[AES256_GCM,data:YdFr7FooxHUIAECPJLZt9jWsc2/t3k/INOYoLUhd1N8=,iv:u4mPjtiyw0NPKDJ3UbcfIAErwcX/HwkF1r7ZqEGOroI=,tag:K7an20YW2Kfxu7bkq5x3Yg==,type:str]
    z: ENC[AES256_GCM,data:jTLVPmPPXFOm9sUUVUA0tBsEFjy9paC1fu6k5coaBYI5JXs6rWOqTkk/Ch8CbrwA8Zef3KuMIAmO2BzSQZaEgLJGKYaJaZfg,iv:qxfqNTLwhaEmrrPtNodAbuqHFKuJCuiLMDlzrvYFRig=,tag:ytC5mgwJuiBgsSQwdHKy1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4cDdRc1hQTGo0eGNwb3Jh
            WE9kZ2t2WEZJRXpDcUpjVFpKWEpJSTBSQWtzCnRIOWdQSFhvcFQwWDlsZHV0V0FW
            YmNDeWZ6aWRqeTJKZHp5WGkyQ25iWUkKLS0tIFBxZGNIaUpFSFlsUFQ1TmJkVW5y
            d0VIT3FoSGpEZ0F1RFd1ZE5IcTAyRUEK60/Gx93iRa7fjV7pfaBQ5au9dezYjIS5
            B0EeRknpM2sGEv0RHTIu5nohJGiEJHWtTlyLQLldzkQykCQLXv6KBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-03T19:54:26Z"
    mac: ENC[AES256_GCM,data:4maHQQtLvGw4e8/L4Zzh2ERAH23fQ/z6C5qt2hphuiUAl1aoRZWPwCG0w+A85+OwdiGoAjGK382sS1hcakVhJZpjg5qFmoB/he/mXuwdtjPpMQ8mqWhx6Bv4z3tSLnCaimpdSRLI1SWIOLQXS2zUfN/JV4g8FprloG3JxBSKEho=,iv:j0JPf/jU4ct/qSwyIcK26TzWm7szAXX4Df84Xpv0VN8=,tag:80UE0T+feYJH3/8QnmWw5w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gitea-credentials
    namespace: default
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:qDrCQZU=,iv:dqRGBarCKjIxHN/3iPi8DjLGEJRyk3Ubb9HsQXdD5HA=,tag:xpFbuB1SixhrxsGqm+DTdA==,type:str]
    password: ENC[AES256_GCM,data:IwOaCHIGdaZWAHZgWSmqZfzy2bLG54JkTKjReWaLXQM=,iv:nNflz5SScyXWiLcJOddUNXuj2S3GWRQ3zbsMQYbxGJw=,tag:RRcp2ETMV9G3oeojwZlsXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4cDdRc1hQTGo0eGNwb3Jh
            WE9kZ2t2WEZJRXpDcUpjVFpKWEpJSTBSQWtzCnRIOWdQSFhvcFQwWDlsZHV0V0FW
            YmNDeWZ6aWRqeTJKZHp5WGkyQ25iWUkKLS0tIFBxZGNIaUpFSFlsUFQ1TmJkVW5y
            d0VIT3FoSGpEZ0F1RFd1ZE5IcTAyRUEK60/Gx93iRa7fjV7pfaBQ5au9dezYjIS5
            B0EeRknpM2sGEv0RHTIu5nohJGiEJHWtTlyLQLldzkQykCQLXv6KBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-03T19:54:26Z"
    mac: ENC[AES256_GCM,data:4maHQQtLvGw4e8/L4Zzh2ERAH23fQ/z6C5qt2hphuiUAl1aoRZWPwCG0w+A85+OwdiGoAjGK382sS1hcakVhJZpjg5qFmoB/he/mXuwdtjPpMQ8mqWhx6Bv4z3tSLnCaimpdSRLI1SWIOLQXS2zUfN/JV4g8FprloG3JxBSKEho=,iv:j0JPf/jU4ct/qSwyIcK26TzWm7szAXX4Df84Xpv0VN8=,tag:80UE0T+feYJH3/8QnmWw5w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
