apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: hef@pbrfrat.com
    preferredChain: ""
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          route53:
            accessKeyID: AKIA3LYTRPMGNDDP27NA
            hostedZoneID: Z03821123JIJDGD4PLWRM
            region: us-east-2
            secretAccessKeySecretRef:
              key: aws_secret_access_key
              name: cert-manager-credentials
        selector:
          dnsZones:
            - hef.sh
