apiVersion: dbman.hef.sh/v1alpha3
kind: Database
metadata:
  name: grafana
  namespace: default
spec:
  credentials:
    basicAuthSecretRef: grafana-db-credentials
  databaseName: grafana
  databaseServerRef:
    namespace: database
    name: postgres
