---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: grafana
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: 7.0.19
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 5m
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    ingress:
      enabled: true
      ingressClassName: internal
      hosts:
        - grafana.${SECRET_DOMAIN}
    persistence:
      enabled: false # defaults to false
    envFromSecret: grafana-secrets
    env:
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: postgres.database.svc.cluster.local
      GF_DATABASE_NAME: grafana
      GF_DATABASE_USER: grafana
