apiVersion: v1
kind: Secret
metadata:
    name: grafana-secrets
    namespace: default
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:NAddp3yoT1MDMAqmy6MzK4jzg1XUjkbdoh/ngbr4SBI=,iv:4P0ltyeTIeHjBCLX+zLZVrBTReCoIHr2iZ1EJllKMBQ=,tag:MoIMOfDhym5ffoOEjRGy4w==,type:str]
    GF_DATABASE_TYPE: ENC[AES256_GCM,data:ODnMmeYv+Mc=,iv:40DIsAWGS0VA1SZpE11pu1IJCIFGzNyEk9VUwnFHqrI=,tag:MLSwebaJWggL6W6KqtK1bw==,type:str]
    GF_DATABASE_HOST: ENC[AES256_GCM,data:/pydiTsk23an0LjxrQwdTYjFyJdIPTbVPg4Q2RnJyvP5G38=,iv:ZGnyS6m9+1JYVPPhlJ63e8m5AaOd1eJ4Qp+Rbj+ngLQ=,tag:eWPmoZmzuUhmOtBsuwIFQQ==,type:str]
    GF_DATABASE_NAME: ENC[AES256_GCM,data:HzGYfzwkfQ==,iv:L1JJnivqwb4QalvMgiVpvOfH/40zQqeZ63EVHP37Oho=,tag:SxQcWh2vY9Gmu2rhtGQEdQ==,type:str]
    GF_DATABASE_USER: ENC[AES256_GCM,data:FfA4SbCTWA==,iv:WZ9RSw3H4yKrLwqeiW4Okq4oEZcxC+7iIIUvx0WSgQI=,tag:5PE2zRNu09iCyFexvLhjIQ==,type:str]
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:j2jIhQ7QTnWYpw/GCyAkuQZvdkQppiB5gV/AvSsMkTM=,iv:lJRqbkadTOO9cR1ZnkEf0w63WQZZ+LvZV+kicZgIMXE=,tag:Liws9jQ91eW+wGAaraWhhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzL2xJMklMUmNtWktSaFZE
            WFVFSVF5dGs5S3AybzQ4b1VCNTJKNVZkUFdFClBsbHF6UTFJeG02TVIzMGFiSkJL
            QjFrWnZNREZUK3pSTGQ3YTRFZzhCREUKLS0tIEVwRC9NTEVTL1dJZ3o0S0ptRCs2
            RHhSK2t4S0NIVGRXQm5CcW4zUVlIV2cKcuf3PCu78CTyq6PtrmBp7n85tGtqVLM2
            IuHr7XKOElYpLu0i0nOsIgiWyvX8ughrhslfCfXh2Vo+5eXS6M/WOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-09T06:12:22Z"
    mac: ENC[AES256_GCM,data:Q9BwgDJ8ACxtu9RoODmpGVtducaUrkfzKtqcSzPH+nI8jJYm5KBXfqqYGP8Tsvf25qTZG4ieajJDMFy+EnKknvR5P+7e+NGP3Lnlp5dG0YKugRaEV4ckxXZyMCiryyO0IkyOvOYAAqGpIYkCPLNpMCisvvKC/7veVhv71afdDPs=,iv:C/1biNz0cJHONckvtGXxWHSZoL+maBl94JLtE2Pjj9s=,tag:JCbblEPSj6iSKnKXf3JYgg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana-db-credentials
    namespace: default
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:eAwk0eujkQ==,iv:aipAD7R/Ji6kk8xLwjqKzp483OOC3PkeL7nNUFZrpZ0=,tag:pxm2wKZWdee8ycgsVL67wg==,type:str]
    password: ENC[AES256_GCM,data:JDyJpdLwz2FSuJyG60W9POHOdDvw2GS20Xk713E/Jqg=,iv:cVoB21jNDMNWxgyVVlR/DUJ4hppwSzjhfYHY8DCmiRY=,tag:emvpIHvq530zfyDJdzSgdg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzL2xJMklMUmNtWktSaFZE
            WFVFSVF5dGs5S3AybzQ4b1VCNTJKNVZkUFdFClBsbHF6UTFJeG02TVIzMGFiSkJL
            QjFrWnZNREZUK3pSTGQ3YTRFZzhCREUKLS0tIEVwRC9NTEVTL1dJZ3o0S0ptRCs2
            RHhSK2t4S0NIVGRXQm5CcW4zUVlIV2cKcuf3PCu78CTyq6PtrmBp7n85tGtqVLM2
            IuHr7XKOElYpLu0i0nOsIgiWyvX8ughrhslfCfXh2Vo+5eXS6M/WOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-09T06:12:22Z"
    mac: ENC[AES256_GCM,data:Q9BwgDJ8ACxtu9RoODmpGVtducaUrkfzKtqcSzPH+nI8jJYm5KBXfqqYGP8Tsvf25qTZG4ieajJDMFy+EnKknvR5P+7e+NGP3Lnlp5dG0YKugRaEV4ckxXZyMCiryyO0IkyOvOYAAqGpIYkCPLNpMCisvvKC/7veVhv71afdDPs=,iv:C/1biNz0cJHONckvtGXxWHSZoL+maBl94JLtE2Pjj9s=,tag:JCbblEPSj6iSKnKXf3JYgg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
