apiVersion: v1
kind: Secret
metadata:
    name: grafana-secrets
    namespace: default
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:ZL76Cvc5mqDUXgEiXv3mmMu3G7gWDvGlgnD6Fpgfdrb1jceDr+GmB1KxX8uxlUy4euudNWhUP8J1HvKabYxX0n6IyiSB/x+7,iv:2v76D30UpMtzZb5/NgPMRZ6fC7ll6h6tQMOE0TVu4dQ=,tag:u2GGM8Y5nefWXFfgn7wImw==,type:str]
    GF_DATABASE_TYPE: ENC[AES256_GCM,data:ODnMmeYv+Mc=,iv:40DIsAWGS0VA1SZpE11pu1IJCIFGzNyEk9VUwnFHqrI=,tag:MLSwebaJWggL6W6KqtK1bw==,type:str]
    GF_DATABASE_HOST: ENC[AES256_GCM,data:/pydiTsk23an0LjxrQwdTYjFyJdIPTbVPg4Q2RnJyvP5G38=,iv:ZGnyS6m9+1JYVPPhlJ63e8m5AaOd1eJ4Qp+Rbj+ngLQ=,tag:eWPmoZmzuUhmOtBsuwIFQQ==,type:str]
    GF_DATABASE_NAME: ENC[AES256_GCM,data:HzGYfzwkfQ==,iv:L1JJnivqwb4QalvMgiVpvOfH/40zQqeZ63EVHP37Oho=,tag:SxQcWh2vY9Gmu2rhtGQEdQ==,type:str]
    GF_DATABASE_USER: ENC[AES256_GCM,data:FfA4SbCTWA==,iv:WZ9RSw3H4yKrLwqeiW4Okq4oEZcxC+7iIIUvx0WSgQI=,tag:5PE2zRNu09iCyFexvLhjIQ==,type:str]
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:j2jIhQ7QTnWYpw/GCyAkuQZvdkQppiB5gV/AvSsMkTM=,iv:lJRqbkadTOO9cR1ZnkEf0w63WQZZ+LvZV+kicZgIMXE=,tag:Liws9jQ91eW+wGAaraWhhw==,type:str]
    INFLUXDB_TOKEN: ENC[AES256_GCM,data:jBGMDXDwmbcdEHoUxm6YoqQzhe6cHjla8keM0Ny8PJ3BtbiI3oDPRtrzcIPllZkKll1R5AoJTwBV8ul/x6TUQFcgylXW3YqkQjC/QRucTejfglGYFMk9Rg==,iv:zFJgJPv2wTL2IDXxgST8dlLCso99CHGKd4+aGknar64=,tag:E7+9AxIQwEm/Smnc4NY4VA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzL2xJMklMUmNtWktSaFZE
            WFVFSVF5dGs5S3AybzQ4b1VCNTJKNVZkUFdFClBsbHF6UTFJeG02TVIzMGFiSkJL
            QjFrWnZNREZUK3pSTGQ3YTRFZzhCREUKLS0tIEVwRC9NTEVTL1dJZ3o0S0ptRCs2
            RHhSK2t4S0NIVGRXQm5CcW4zUVlIV2cKcuf3PCu78CTyq6PtrmBp7n85tGtqVLM2
            IuHr7XKOElYpLu0i0nOsIgiWyvX8ughrhslfCfXh2Vo+5eXS6M/WOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-15T19:07:17Z"
    mac: ENC[AES256_GCM,data:oxP/pgk13Q3rAcWelvkNS3D3znOTEl7JwBj6HvvgVjTBrbR+z9p+obQGm5nRJZ9GhBN94ZmdIvUQVtp9WVqCrGQp+QdECrHOdeWiqzf+uRaMTnMqbA+TYWubBzuAVyVI86BlcGU4RWiMu0EoIk4QrR7hwcwXRIkQ5njsqcHMB4Q=,iv:RVxYadeX/kfCdrimwm9sTO5CU6HukPIH5M5wW6H85AA=,tag:cxFK0YWfpAOGMJBRCZrq4A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana-db-credentials
    namespace: default
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:eAwk0eujkQ==,iv:aipAD7R/Ji6kk8xLwjqKzp483OOC3PkeL7nNUFZrpZ0=,tag:pxm2wKZWdee8ycgsVL67wg==,type:str]
    password: ENC[AES256_GCM,data:JDyJpdLwz2FSuJyG60W9POHOdDvw2GS20Xk713E/Jqg=,iv:cVoB21jNDMNWxgyVVlR/DUJ4hppwSzjhfYHY8DCmiRY=,tag:emvpIHvq530zfyDJdzSgdg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzL2xJMklMUmNtWktSaFZE
            WFVFSVF5dGs5S3AybzQ4b1VCNTJKNVZkUFdFClBsbHF6UTFJeG02TVIzMGFiSkJL
            QjFrWnZNREZUK3pSTGQ3YTRFZzhCREUKLS0tIEVwRC9NTEVTL1dJZ3o0S0ptRCs2
            RHhSK2t4S0NIVGRXQm5CcW4zUVlIV2cKcuf3PCu78CTyq6PtrmBp7n85tGtqVLM2
            IuHr7XKOElYpLu0i0nOsIgiWyvX8ughrhslfCfXh2Vo+5eXS6M/WOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-15T19:07:17Z"
    mac: ENC[AES256_GCM,data:oxP/pgk13Q3rAcWelvkNS3D3znOTEl7JwBj6HvvgVjTBrbR+z9p+obQGm5nRJZ9GhBN94ZmdIvUQVtp9WVqCrGQp+QdECrHOdeWiqzf+uRaMTnMqbA+TYWubBzuAVyVI86BlcGU4RWiMu0EoIk4QrR7hwcwXRIkQ5njsqcHMB4Q=,iv:RVxYadeX/kfCdrimwm9sTO5CU6HukPIH5M5wW6H85AA=,tag:cxFK0YWfpAOGMJBRCZrq4A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
