---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: database
  annotations:
    external-dns.alpha.kubernetes.io/hostname: postgres.${SECRET_DOMAIN}
    io.cilium/lb-ipam-ips: 192.168.1.6
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres
    cnpg.io/instanceRole: primary
---
apiVersion: v1
kind: Service
metadata:
  name: db16
  namespace: database
  annotations:
    external-dns.alpha.kubernetes.io/hostname: postgres.${SECRET_DOMAIN}
    io.cilium/lb-ipam-ips: 192.168.1.13
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres16
    cnpg.io/instanceRole: primary
