---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config
  namespace: home
spec:
  volumeName: home-assistant-config
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  #storageClassName: longhorn-static
