apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whisper
  template:
    metadata:
      labels:
        app: whisper
    spec:
      containers:
        - name: whisper
          image: rhasspy/wyoming-whisper:1.0.0
          ports:
            - containerPort: 10300
          volumeMounts:
          - name: data
            mountPath: /data
      volumes:
        - name: data
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes: [ "ReadWriteOnce" ]
                resources:
                  requests:
                    storage: 1Gi
                storageClassName: local-path