---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  releaseName: longhorn
  interval: 30m
  chart:
    spec:
      chart: longhorn
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
  values:
    defaultSettings:
      backupTarget: s3://longhorn-20201224060010162400000001@us-east-2/
      backupTargetCredentialSecret: aws-secret
      defaultDataLocality: best-effort
      replicaAutoBalance: best-effort
      nodeDownPodDeletionPolicy:  delete-both-statefulset-and-deployment-pod
      mkfsExt4Parameters: -F
    persistence:
      recurringJobSelector:
        enabled: true
        jobList: '[{"name":"daily-backup", "isGroup":false}]'
    ingress:
      enabled: true
      host: longhorn.hef.sh
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/icon: "harddisk"
