apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    persistence:
      enabled: true
      existingClaim: loki
