# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:c4k7yXmTroWgAVY1IxVQPlpqcgNXPWbCzzKD43LpVF8/xgUixA==,iv:+QXY0D3hU2BoG0M41T1u27E7a1fWAyvQGrEthBsRZFE=,tag:seu2h2OaIv88seSsmznHpw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZVp1SUgwZCsrUkZyWFZS
            aTllTU5oenNLMm5kY1c2ZEtwRDAxNXlaMndjCldPa1NnbDhBVzdTMHl6OWRKZDIz
            WE5WZ2U3bHlXZ0JaR1FWby8rbVBkS28KLS0tIGlqSUZ5MkJsMHYwMG1RMDNMd3U5
            SUsvS2JVY2hwSWpHVlp1c21aenV4d1UKLk3L0pjO+gDuU1UKIMDHQ7B1nDMyXHUO
            /FtR+04hJxVFnXndQNCuE1cZ1uwFaoLryCYq8ZWhmPlqaxqc66Fj5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-19T10:00:27Z"
    mac: ENC[AES256_GCM,data:LYRAl/A8KH0iuul7oQ9NTHGJjHGaYGkxm/zPzxCY4OT02TRVneN0ZNYALJeVj8ou0L+bJVt+30cvnYl36Mu0H3plqfqLGKdm2C9MGoRWEEUm7B9vHG1/P3bfxsDoqj+kw7eYDvTU7MNe7gDdE6wVIReud/RW8KCVjYPZ562wuBM=,iv:M9k+Bck+Sr0shHE8joUreO7qXoVdyKDNNZiy5VlsvI0=,tag:N1WAXvE1sZuj6rG2LAxtsQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
