---
# https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/
# https://github.com/PyratLabs/ansible-role-k3s

# (bool) Specify if a host (or host group) are part of the control plane
k3s_control_node: true

# (dict) k3s settings for all control-plane nodes
k3s_server:
  node-ip: "{{ ansible_host }}"
  tls-san:
    # kube-vip
    - "{{ kube_vip_addr }}"
  docker: false
  flannel-backend: "none" # This needs to be in quotes
  disable:
    - coredns
    - flannel
    - local-storage
    - metrics-server
    - servicelb
    - traefik
  disable-network-policy: true
  disable-cloud-controller: true
  disable-kube-proxy: true
  write-kubeconfig-mode: "644"
  # Network CIDR to use for pod IPs
  cluster-cidr: "10.42.0.0/16"
  # Network CIDR to use for service IPs
  service-cidr: "10.43.0.0/16"
  #kubelet-arg:
  kube-controller-manager-arg:
    - "bind-address=0.0.0.0"
  #kube-proxy-arg:
  kube-scheduler-arg:
    - "bind-address=0.0.0.0"
  etcd-expose-metrics: true
  kube-apiserver-arg:
    - "anonymous-auth=true"
