apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority
value: 1000000
globalDefault: false
# cnpg clusters sometimes need to evict pods from arm64 nodes to run on arm64 nodes.
description: "This priority class should be used for database workloads."
