---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          init-config:
            image:
              repository: public.ecr.aws/docker/library/eclipse-mosquitto
              tag: 2.0.18
              pullPolicy: IfNotPresent
            command: ["/bin/sh", "-c"]
            args: ["cp /tmp/secret/* /mosquitto/external_config/ && mosquitto_passwd -U /mosquitto/external_config/mosquitto_pwd"]
          main:
            image:
              repository: public.ecr.aws/docker/library/eclipse-mosquitto
              tag: 2.0.18
            env:
              TZ: america/chicago
            resources:
              requests:
                cpu: 5m
                memory: 4Mi
              limits:
                memory: 16Mi
    persistence:
      config:
        type: configMap
        name: mosquitto-configmap
        advanceMounts:
          main:
            main:
              - path: /mosquitto/config/mosquitto.conf
                subPath: mosquitto.conf
      secret:
        type: secret
        name: mosquitto-secret
        advancedMounts:
          main:
            init-config:
              - path: /tmp/secret
      external-config:
        type: emptyDir
        globalMounts:
          - path: /mosquitto/external_config
      data:
        enabled: true
        mountPath: /data
        accessMode: ReadWriteOnce
        type: persistentVolumeClaim
        size: 1Gi
        storageClass: longhorn
    service:
      main:
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: mosquitto.${SECRET_DOMAIN}
          io.cilium/lb-ipam-ips: 192.168.1.8
        ports:
          http:
            enabled: false
          mqtt:
            enabled: true
            port: 1883
