apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-secret
    namespace: default
stringData:
    zigbee2mqtt_user: ENC[AES256_GCM,data:if/imDQTGSC8EGg=,iv:ixpuxbcL1BQwELK+MoBiZwGTifcmY54ULW2c9CGs8gw=,tag:eJk8bDXPW+AApzHacleUNw==,type:str]
    zigbee2mqtt_password: ENC[AES256_GCM,data:HmgNPjTe0nl9ATwJ8NI5gCnbwXPJOo0Q5Zf2rZ9nRm4=,iv:ryLP1b1kOCt741kepGSKozN+qtb0SznJAonWhIhPO18=,tag:eOwpbibYmKqZypPJUv9Lig==,type:str]
    mosquitto_pwd: ENC[AES256_GCM,data:bs5n5N0QbYQcpZTTzbVZSchqSTT+viRjOjkq98msZZLKLa7fnHv4xqgXTrKZ,iv:2bRRTXAGnUJr9ISAEy2rNW1v08e9URqWzhQYuQIv05A=,tag:xr04QEPt1IYjTItqEx//yg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSEF3bzdLR0Z3WHJVeGJP
            WnRDcGxDdjZKbVp0NE9KZkR2a1VkVVhaZUFNClY3cU5iMWVLQUJXeUdqWE1hNE0y
            czdianNVNVNFSTJKQjJXQkdINEdHdUEKLS0tIG5vTG44djNNaElVZ3BYZllkTmMy
            VkhLVFdNR2FvMjNiMVRPbUFGWEwxZFkKiXt4wfgMZTi0fUqgCtr4xZ9x4JCmRgaI
            tQ8sCPiwDWERB/QGbuoYPWIkwosvAvHtps+tlw6AywmR3WeYn/lJTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-04T03:27:11Z"
    mac: ENC[AES256_GCM,data:/5GVbq3dHbKsUBM65hW9qdxIXluFr06wSRwYQ0DFbufKJqrTXIkChQwILCM6FoZFLpkj5w39CgdItVH7wQBp9WCHC+ePMgmug1l7TVXMzeQ9Hxzbh+eBzHPZE4uEHM1ydu1+A4A4GVVkIe5omb2047M9ZNRIeQ2uwx8uu06xSLU=,iv:LDjR2yCu6Zah5NZf/VtAc2hvZFyKeOCSOeCK+gzzWiY=,tag:4P7/0cFu+alNz0bWaKBa6w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
