apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-secret
    namespace: default
stringData:
    zigbee2mqtt_user: ENC[AES256_GCM,data:if/imDQTGSC8EGg=,iv:ixpuxbcL1BQwELK+MoBiZwGTifcmY54ULW2c9CGs8gw=,tag:eJk8bDXPW+AApzHacleUNw==,type:str]
    zugbee2mqtt_password: ENC[AES256_GCM,data:Rk8ZL7ZlS+r6w4xvW4LzpIITmY86J/ftqbiEG/JO+Bw=,iv:WAGezHB0eNf2csViLW1o88HJOpCHEMtgM8/CtnkbBgA=,tag:wzsWCBlrvdqDLWmNJouPIA==,type:str]
    mosquitto_pwd: ENC[AES256_GCM,data:bs5n5N0QbYQcpZTTzbVZSchqSTT+viRjOjkq98msZZLKLa7fnHv4xqgXTrKZ,iv:2bRRTXAGnUJr9ISAEy2rNW1v08e9URqWzhQYuQIv05A=,tag:xr04QEPt1IYjTItqEx//yg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSEF3bzdLR0Z3WHJVeGJP
            WnRDcGxDdjZKbVp0NE9KZkR2a1VkVVhaZUFNClY3cU5iMWVLQUJXeUdqWE1hNE0y
            czdianNVNVNFSTJKQjJXQkdINEdHdUEKLS0tIG5vTG44djNNaElVZ3BYZllkTmMy
            VkhLVFdNR2FvMjNiMVRPbUFGWEwxZFkKiXt4wfgMZTi0fUqgCtr4xZ9x4JCmRgaI
            tQ8sCPiwDWERB/QGbuoYPWIkwosvAvHtps+tlw6AywmR3WeYn/lJTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-04T03:22:55Z"
    mac: ENC[AES256_GCM,data:lgvGjui6YXu4HF8D4OvdboVuq8oGDmMJotegQqcMAEeUGrD4DHkHFR7bR5rxiI8O0ruUnVqLLRcQGmXH5HZpIFE41bXD6E+rMvsuO9/6PpsAkISeGlQ/UHrrupsufMaAQtM0Erlz7V2q+4QY2iCDpasNq0181ma/oS4CeUlcPoA=,iv:Vwi+PrNU8uoSLMda73n/Chk+d68ByeDLv0/8S03mla0=,tag:KHmxDoUgNd6z+TuWCm6wkA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
