apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-secret
    namespace: default
stringData:
    mosquito_pwd: ENC[AES256_GCM,data:pPE0FMKqn/G/8iXRpRHGe+Twkxf/3loqRz0H4YAjBiIQ1YWnwcjr9XA9cz65,iv:Nj1uVc4tNpf+jNx0p/uJA2216aSdA+PiObX0MDCK5O8=,tag:g/WRdg1ixNkrdnMEkabtQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSEF3bzdLR0Z3WHJVeGJP
            WnRDcGxDdjZKbVp0NE9KZkR2a1VkVVhaZUFNClY3cU5iMWVLQUJXeUdqWE1hNE0y
            czdianNVNVNFSTJKQjJXQkdINEdHdUEKLS0tIG5vTG44djNNaElVZ3BYZllkTmMy
            VkhLVFdNR2FvMjNiMVRPbUFGWEwxZFkKiXt4wfgMZTi0fUqgCtr4xZ9x4JCmRgaI
            tQ8sCPiwDWERB/QGbuoYPWIkwosvAvHtps+tlw6AywmR3WeYn/lJTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-04T01:58:24Z"
    mac: ENC[AES256_GCM,data:ORhz84RxEkqcDW8yFdKKM9HMv94j3brpuJQ4658FdKoJi5uG8S+ijn3C5+LXIYujOKffrOVxxEuJ/VKL3hUMeyHU38NI/PG/Q+a27KRZlIugas5a4h8P8VxYeJAaFwjPd1Oo4+iR90q6R8AgPuXrVqFELTQC6CWsP02XUegpBPk=,iv:X44tUqdnsdTzhGKh78TQ5afIrdHm1LTmMHJqHyZuh9E=,tag:Q73qZzfWP+/AyiPCQI9zSw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
