---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blocky
  namespace: blocky
spec:
  interval: 5m
  chart:
    spec:
      chart: blocky
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    env:
      TZ: ${SECRET_TZ}
    service:
      dns-tcp:
        type: LoadBalancer
        loadBalancerIP: 192.168.4.4
        annotations:
          metallb.universe.tf/allow-shared-ip: dns
        enabled: true
      dns-udp:
        type: LoadBalancer
        loadBalancerIP: 192.168.4.4
        annotations:
          metallb.universe.tf/allow-shared-ip: dns
        enabled: true
    config: |
      upstream:
        externalResolvers:
          - 46.182.19.48
          - 80.241.218.68
          - tcp-tls:fdns1.dismail.de:853
          - https://dns.digitale-gesellschaft.ch/dns-query
      customDNS:
        mapping:
          printer.lan: 192.168.178.3
      conditional:
        mapping:
          hef.sh: udp:192.168.4.3
      blocking:
        blackLists:
          ads:
            - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
            - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
            - https://mirror1.malwaredomains.com/files/justdomains
            - http://sysctl.org/cameleon/hosts
            - https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist
            - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
          special:
            - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews/hosts
        whiteLists:
          ads:
            - whitelist.txt
        clientGroupsBlock:
          default:
            - ads
            - special
          laptop*:
            - ads
          192.168.178.1/24:
            - special
        blockType: zeroIp
        refreshPeriod: 0
      caching:
        minTime: 5
        maxTime: 0
        prefetching: true
      clientLookup:
        upstream: udp:192.168.1.1
        singleNameOrder:
          - 2
          - 1
        clients:
          laptop:
            - 192.168.178.29
      prometheus:
        enable: true
        path: /metrics
      port: 53
      httpPort: 4000
      bootstrapDns: tcp:1.1.1.1
      logLevel: info
      logFormat: json
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 750Mi
