---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app pgadmin
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: pgadmin4
      version: 1.19.0
      sourceRef:
        kind: HelmRepository
        name: runix
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    strategy:
      type: Recreate
    env:
      TZ: ${SECRET_TZ}
    ingress:
      enabled: true
      ingressClassName: internal
      hosts:
        - host: pgadmin.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
    persistentVolume:
      size: 1Gi
      storageClass: longhorn
