---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app pgadmin
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: pgadmin4
      version: 1.20.0
      sourceRef:
        kind: HelmRepository
        name: runix
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    strategy:
      type: Recreate
    env:
      TZ: ${SECRET_TZ}
      AUTHENTICATION_SOURCES: "['internal']"
      PGADMIN_CONFIG_OAUTH2_NAME: "Authelia"
      PGADMIN_CONFIG_OAUTH2_DISPLAY_NAME: "Authelia"
      PGADMIN_CONFIG_OAUTH2_CLIENT_ID: "pgadmin"
      PGADMIN_CONFIG_OAUTH2_TOKEN_URL: "https://auth.${SECRET_DOMAIN}/api/oidc/token"
      PGADMIN_CONFIG_OAUTH2_AUTHORIZATION_URL: "https://auth.${SECRET_DOMAIN}/api/oidc/authorization"
      PGADMIN_CONFIG_OAUTH2_SERVER_METADATA_URL: "https://auth.${SECRET_DOMAIN}/.well-known/openid-configuration"
      PGADMIN_CONFIG_OAUTH2_API_BASE_URL: "https://auth.${SECRET_DOMAIN}/api/oidc/userinfo"
      PGADMIN_CONFIG_OAUTH2_USERINFO_ENDPOINT: "https://auth.${SECRET_DOMAIN}/api/oidc/userinfo"
      PGADMIN_CONFIG_OAUTH2_SCOPE: "openid profile email groups"
      #PGADMIN_CONFIG_OAUTH2_ICON: "fa-signin"
      #PGADMIN_CONFIG_OAUTH2_BUTTON_COLOR: "#ffffff"
    envVarsFromSecrets:
      - pgadmin-secrets
    ingress:
      enabled: true
      ingressClassName: internal
      hosts:
        - host: pgadmin.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
    persistentVolume:
      size: 1Gi
      storageClass: longhorn
