---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app pgadmin
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: pgadmin4
      version: 1.23.1
      sourceRef:
        kind: HelmRepository
        name: runix
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    annotations:
      reloader.stakater.com/auto: "true"
    strategy:
      type: Recreate
    env:
      TZ: ${SECRET_TZ}
    envVarsFromSecrets:
      - pgadmin-secrets
      - pgadmin-credentials
    extraConfigmapMounts:
      - name: pgadmin-config
        mountPath: /pgadmin4/config_local.py
        subPath: config_local.py
        configMap: pgadmin-config
        readOnly: true
    ingress:
      enabled: true
      ingressClassName: internal
      hosts:
        - host: pgadmin.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
    persistentVolume:
      size: 1Gi
      storageClass: longhorn
