---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app pgadmin
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: runix
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: runix
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    env:
      TZ: America/Chicago
    ingress:
      enabled: true
      ingressClassName: internal
      hosts:
        - host: pgadmin.${SECRET_DOMAIN}
