apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-secrets
    namespace: default
stringData:
    PGADMIN_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:5vk8OelBjJBwXVsMD5zxgf0tLAyB0Yu3H6pj/TvNNNhytQyrfFituNLBoAqtYjo2oeZRyt7rTnZK1cnPd0bRrbP7rQd0FYYG,iv:bvUgvJ+0wlH7Ddw9JStjNCCUXQ3/e3PlyEtZiM8lacM=,tag:FaJc9nQdLbYH004APxFDBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVW93UVIrcUhHVXRCZE15
            TWJDT0FOT3VZUWo5SVFFRERVMHU1eG4xRlM0ClJ2eVR3ZXpyOVZOV3FuMk9sRWxI
            VFpFRE1iWTYvV1lmeU0xd2F6aFUxZUEKLS0tIEltWHlTQWVZRkhMYVJnZmhzSStT
            aGlERm1EZlJveS9Vb1Q5dWtlMWRMcTAKno3Y18wZ6pr8AlfFIvI0XxmXmeprKUs9
            RHRBxASvCMZF5n9FAxNnWkPlJMPr6kAWiFgbvCX86oLfmTwtt3Ki5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-10T02:19:01Z"
    mac: ENC[AES256_GCM,data:EhSirxPYLLC61eg4FPJk+DElL7fhltkvUDDK27L3NfujQghnvgeT0XW7uzGb+HIZRI0TbJOv59cGxQA614+gSq1/rP3N3vU3+oO81hIQED/WDJamdxg9Au5QIiHcXhHP/CVM3BY/cj8v3WmWHbDUtoBMTLsX0ONhbqP7MNqU+Bk=,iv:WKRmuv8z9KU2tMQrdgPOWPRJXxIsV/NPk95IHWTtYZk=,tag:orcM3ROJNb2Vf5kR6UrcTg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
