apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-secrets
    namespace: default
stringData:
    OAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:nA355JrgunyMpQ2cNtrFkny9nf1D4KtarF6ouQK0ykbkl5KtT57JFeMjt3vqjB9U2wz82WmExNCvtM/RwwaFF9Qi/+GRAQrM,iv:oluXbUV8hZf5NgvCWk3iuvR7vS0O0Cg2aFu6rCy1S58=,tag:Gfi3qQROyPsqf4MCggryTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVW93UVIrcUhHVXRCZE15
            TWJDT0FOT3VZUWo5SVFFRERVMHU1eG4xRlM0ClJ2eVR3ZXpyOVZOV3FuMk9sRWxI
            VFpFRE1iWTYvV1lmeU0xd2F6aFUxZUEKLS0tIEltWHlTQWVZRkhMYVJnZmhzSStT
            aGlERm1EZlJveS9Vb1Q5dWtlMWRMcTAKno3Y18wZ6pr8AlfFIvI0XxmXmeprKUs9
            RHRBxASvCMZF5n9FAxNnWkPlJMPr6kAWiFgbvCX86oLfmTwtt3Ki5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-11T22:52:39Z"
    mac: ENC[AES256_GCM,data:kN4PRDNkeQky2SWxKyIQDvSdOCUHkUIz4+sR+hXXh3Yn2BYfCd4uetUV7V75Do3mFqaZY5f1nhm9k/aqMvi9X+iRaB8T/0S3ETG2KnKFTZuvKg2SKQReAESs9rg1amXzgZ7BiHytN54zIdjXXFWCcDzYGSfvqJ/2s3T69b0YUxk=,iv:L3PPMut0WR/CTcIw8xh/epax+sZD37i8xAiXYkHtw9E=,tag:vrc27IqlqfDJdbfzNHZY4A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-credentials
    namespace: default
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:KjnXhXwBzw==,iv:3T3jiJYmaqjPlHY0o4MjBLNAvIoKDy4HuXgmR90vkro=,tag:Skr3xKAgq6xe9XQZspXh9A==,type:str]
    password: ENC[AES256_GCM,data:0/IM/Vihzd0mTZWGPtpckHYsnwXss9R0bPifAvz6HvM=,iv:BULNfhYEkHM50i/FZV+9KkLeea8cxgV2ULpK6wpCu2k=,tag:Sk+B2PFsvXkAFwxwgPd5Wg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVW93UVIrcUhHVXRCZE15
            TWJDT0FOT3VZUWo5SVFFRERVMHU1eG4xRlM0ClJ2eVR3ZXpyOVZOV3FuMk9sRWxI
            VFpFRE1iWTYvV1lmeU0xd2F6aFUxZUEKLS0tIEltWHlTQWVZRkhMYVJnZmhzSStT
            aGlERm1EZlJveS9Vb1Q5dWtlMWRMcTAKno3Y18wZ6pr8AlfFIvI0XxmXmeprKUs9
            RHRBxASvCMZF5n9FAxNnWkPlJMPr6kAWiFgbvCX86oLfmTwtt3Ki5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-11T22:52:39Z"
    mac: ENC[AES256_GCM,data:kN4PRDNkeQky2SWxKyIQDvSdOCUHkUIz4+sR+hXXh3Yn2BYfCd4uetUV7V75Do3mFqaZY5f1nhm9k/aqMvi9X+iRaB8T/0S3ETG2KnKFTZuvKg2SKQReAESs9rg1amXzgZ7BiHytN54zIdjXXFWCcDzYGSfvqJ/2s3T69b0YUxk=,iv:L3PPMut0WR/CTcIw8xh/epax+sZD37i8xAiXYkHtw9E=,tag:vrc27IqlqfDJdbfzNHZY4A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-pgadmin4-backup-config
    namespace: default
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:G1RMoMMjB0YftETrHhlyr0jt4oBBoVj8nMPdFUMic8wh/+zaF60hJ6SaJl9poqNWhroNFzRIFNEq8+IFW7ursYP8BULB,iv:lcU1upRu80RDQfxZeDpKf31VFv/iZruESZFyxsnvUKg=,tag:D9Rh4zLnOVRafI/qy5nkfw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:4cGxvFsAKWOzWZ51r41sLtx9saqefcytOI0o0Gee7/gCVgGcMzhtmVvCVaa3jub8O7VVbdCuKjGcPQ85ZavigjOBSPL+IAP41P8yNpdXau4JYRGPOf49GTm6oAnWh8xRb0uOX/k3FRMwDM/k6yFE+1fizo6P4YfbUSfMFY/4Efs=,iv:RsPJiZTfv0rJrtSgQ3iYSqB8Yv26jucYqMHCE85Deos=,tag:Gz0WPxgNsCMHx7kHL+f1mQ==,type:str]
    #ENC[AES256_GCM,data:GL6AeceeI2yudBjzl4FX2CQSqotxOaKsG2UMMDlDQDG4aIKBpcJdcjk=,iv:My1jNIuwOuVUhUw+UwpFA/BUb9Y1AeBt9boHfV48yDs=,tag:pFBkUIMnQzge8/q9fXZ1hw==,type:comment]
    #ENC[AES256_GCM,data:wIEDkNNlVCIt5bd1qtxBah07Kgknjo621BHL9X8Fz63BYp4CSm0+hJbNJuOWyQMbSpIMMRgXqnmAjfJy29nnYNXsoRcuKw==,iv:x5WpzLjW8CHvx1wW4klOfao+WS+hGGHQHtrI2mcO91w=,tag:HDMLLUNFrxESrQrtKLiDHw==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:5lVek9/HLxg3r62Y5GwiK+sxMQdtzxknmg==,iv:PLdG5z3wGlEGjnKfno8PzL4FOT8U9PsIfQm/dnhBf4E=,tag:nlfBXjEMJSfjVGhyHB/CKw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:3Fhos9nQDSVjIZbKS9nwBy5Ez01RWMXpJY4eFMk1JA==,iv:EjjLza3QdgBHAa/7Uje/czcNQDvsuuFvSLKHzy24Kdw=,tag:e+PrkNhXTMrmcfVtI5WKDA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVW93UVIrcUhHVXRCZE15
            TWJDT0FOT3VZUWo5SVFFRERVMHU1eG4xRlM0ClJ2eVR3ZXpyOVZOV3FuMk9sRWxI
            VFpFRE1iWTYvV1lmeU0xd2F6aFUxZUEKLS0tIEltWHlTQWVZRkhMYVJnZmhzSStT
            aGlERm1EZlJveS9Vb1Q5dWtlMWRMcTAKno3Y18wZ6pr8AlfFIvI0XxmXmeprKUs9
            RHRBxASvCMZF5n9FAxNnWkPlJMPr6kAWiFgbvCX86oLfmTwtt3Ki5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-11T22:52:39Z"
    mac: ENC[AES256_GCM,data:kN4PRDNkeQky2SWxKyIQDvSdOCUHkUIz4+sR+hXXh3Yn2BYfCd4uetUV7V75Do3mFqaZY5f1nhm9k/aqMvi9X+iRaB8T/0S3ETG2KnKFTZuvKg2SKQReAESs9rg1amXzgZ7BiHytN54zIdjXXFWCcDzYGSfvqJ/2s3T69b0YUxk=,iv:L3PPMut0WR/CTcIw8xh/epax+sZD37i8xAiXYkHtw9E=,tag:vrc27IqlqfDJdbfzNHZY4A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
