---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: esphome
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        replicas: 1
        strategy: Recreate
        containers:
          main:
            image:
              repository: ghcr.io/esphome/esphome
              tag: 2023.12.1@sha256:cba7f28241c09a738e60abb6f41de7d406422885d1cec22ca0b394d7f363af69
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 10m
                memory: 500Mi
              limits:
                memory: 2Gi
            env:
              TZ: America/Chicago
        pod:
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
    service:
      main:
        #annotations:
        #  io.cilium/lb-ipam-ips: 192.168.1.7
        ports:
          http:
            port: 6052
          api:
            port: 6053
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          hajimari.io/enable: "true"
        hosts:
          - host: &host esphome.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      #esphome-cache:
      #  enabled: true
      #  type: emptyDir
      #  mountPath: /cache
      config:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 5Gi
        mountPath: /config
        storageClass: longhorn
